In [ ]:
import pandas as pd
import numpy as np

# ============================================================
# CASE STUDY 6
# SUPPLY CHAIN & INVENTORY MANAGEMENT
# STEP 1: LOAD SOURCE DATA
# ============================================================

# Load datasets
sales = pd.read_csv('/content/sales_data-2.csv')
inventory = pd.read_csv('/content/inventory_data.csv')
suppliers = pd.read_csv('/content/suppliers_data.csv')
purchase_orders = pd.read_csv('/content/purchase_orders_data.csv')

# ============================================================
# DISPLAY BASIC INFORMATION
# ============================================================

datasets = {
    "Sales": sales,
    "Inventory": inventory,
    "Suppliers": suppliers,
    "Purchase Orders": purchase_orders
}

for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(f"{name.upper()} DATASET")
    print("=" * 70)

    print(f"Rows    : {df.shape[0]}")
    print(f"Columns : {df.shape[1]}")

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    display(df.head())

======================================================================
SALES DATASET
======================================================================
Rows    : 5000
Columns : 6

Columns:
['Sale_ID', 'Product_ID', 'Store_ID', 'Sale_Date', 'Quantity_Sold', 'Revenue']

First 5 rows:

    Sale_ID Product_ID Store_ID   Sale_Date  Quantity_Sold  Revenue
0  0d12b607       P001     S102  2024-01-01            322     2556
1  2e13fe47       P003     S101  2024-01-02             28    42606
2  c05afd2d       P003     S104  2024-01-03            292    19551
3  aff62361       P004     S101  2024-01-04            280    26625
4  9d190af1       P003     S101  2024-01-05            353    24001

======================================================================
INVENTORY DATASET
======================================================================
Rows    : 200
Columns : 6

Columns:
['Product_ID', 'Store_ID', 'Warehouse_ID', 'Stock_Level', 'Reorder_Level', 'Last_Updated']

First 5 rows:

  Product_ID Store_ID Warehouse_ID  Stock_Level  Reorder_Level Last_Updated
0       P005     S101         W003          498            163   2024-02-01
1       P004     S103         W003           24            178   2024-02-02
2       P002     S101         W002          245            188   2024-02-03
3       P003     S101         W003           61            148   2024-02-04
4       P002     S101         W002           57            155   2024-02-05

======================================================================
SUPPLIERS DATASET
======================================================================
Rows    : 50
Columns : 5

Columns:
['Supplier_ID', 'Supplier_Name', 'Product_ID', 'Lead_Time (days)', 'Order_Frequency']

First 5 rows:

,Supplier_ID,Supplier_Name,Product_ID,Lead_Time (days),Order_Frequency
0,SUP001,Murray-Ramirez,P002,9,Weekly
1,SUP002,"Thomas, Meyer and Campbell",P005,9,Weekly
2,SUP003,Acosta Inc,P005,4,Monthly
3,SUP004,"Evans, Brown and Turner",P002,8,Weekly
4,SUP005,"Johnson, Wise and Barr",P003,6,Biweekly

======================================================================
PURCHASE ORDERS DATASET
======================================================================
Rows    : 1000
Columns : 6

Columns:
['Order_ID', 'Product_ID', 'Supplier_ID', 'Order_Date', 'Quantity', 'Arrival_Date']

First 5 rows:

  Order_ID Product_ID Supplier_ID  Order_Date  Quantity Arrival_Date
0   PO0001       P001      SUP002  2024-01-01       158   2024-01-06
1   PO0002       P005      SUP019  2024-01-02       440   2024-01-07
2   PO0003       P002      SUP036  2024-01-03       423   2024-01-08
3   PO0004       P004      SUP021  2024-01-04        88   2024-01-09
4   PO0005       P001      SUP002  2024-01-05       329   2024-01-10

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 2: DATA QUALITY CHECK
# ============================================================

for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(f"{name.upper()} - DATA QUALITY CHECK")
    print("=" * 70)

    # Data types
    print("\n1. DATA TYPES")
    print(df.dtypes)

    # Missing values
    print("\n2. MISSING VALUES")
    missing = df.isnull().sum()
    print(missing)

    # Duplicate rows
    print("\n3. DUPLICATE ROWS")
    print("Duplicate rows:", df.duplicated().sum())

    # Unique values
    print("\n4. UNIQUE VALUES")
    print(df.nunique())

======================================================================
SALES - DATA QUALITY CHECK
======================================================================

1. DATA TYPES
Sale_ID          object
Product_ID       object
Store_ID         object
Sale_Date        object
Quantity_Sold     int64
Revenue           int64
dtype: object

2. MISSING VALUES
Sale_ID          0
Product_ID       0
Store_ID         0
Sale_Date        0
Quantity_Sold    0
Revenue          0
dtype: int64

3. DUPLICATE ROWS
Duplicate rows: 0

4. UNIQUE VALUES
Sale_ID          5000
Product_ID          5
Store_ID            4
Sale_Date        5000
Quantity_Sold     490
Revenue          4764
dtype: int64

======================================================================
INVENTORY - DATA QUALITY CHECK
======================================================================

1. DATA TYPES
Product_ID       object
Store_ID         object
Warehouse_ID     object
Stock_Level       int64
Reorder_Level     int64
Last_Updated     object
dtype: object

2. MISSING VALUES
Product_ID       0
Store_ID         0
Warehouse_ID     0
Stock_Level      0
Reorder_Level    0
Last_Updated     0
dtype: int64

3. DUPLICATE ROWS
Duplicate rows: 0

4. UNIQUE VALUES
Product_ID         5
Store_ID           4
Warehouse_ID       3
Stock_Level      168
Reorder_Level    111
Last_Updated     200
dtype: int64

======================================================================
SUPPLIERS - DATA QUALITY CHECK
======================================================================

1. DATA TYPES
Supplier_ID         object
Supplier_Name       object
Product_ID          object
Lead_Time (days)     int64
Order_Frequency     object
dtype: object

2. MISSING VALUES
Supplier_ID         0
Supplier_Name       0
Product_ID          0
Lead_Time (days)    0
Order_Frequency     0
dtype: int64

3. DUPLICATE ROWS
Duplicate rows: 0

4. UNIQUE VALUES
Supplier_ID         50
Supplier_Name       50
Product_ID           5
Lead_Time (days)     7
Order_Frequency      3
dtype: int64

======================================================================
PURCHASE ORDERS - DATA QUALITY CHECK
======================================================================

1. DATA TYPES
Order_ID        object
Product_ID      object
Supplier_ID     object
Order_Date      object
Quantity         int64
Arrival_Date    object
dtype: object

2. MISSING VALUES
Order_ID        0
Product_ID      0
Supplier_ID     0
Order_Date      0
Quantity        0
Arrival_Date    0
dtype: int64

3. DUPLICATE ROWS
Duplicate rows: 0

4. UNIQUE VALUES
Order_ID        1000
Product_ID         5
Supplier_ID       50
Order_Date      1000
Quantity         406
Arrival_Date    1000
dtype: int64

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 3: DATE CONVERSION & DATE RANGE VALIDATION
# ============================================================

# Convert date columns to datetime
sales['Sale_Date'] = pd.to_datetime(sales['Sale_Date'], errors='coerce')

inventory['Last_Updated'] = pd.to_datetime(
    inventory['Last_Updated'],
    errors='coerce'
)

purchase_orders['Order_Date'] = pd.to_datetime(
    purchase_orders['Order_Date'],
    errors='coerce'
)

purchase_orders['Arrival_Date'] = pd.to_datetime(
    purchase_orders['Arrival_Date'],
    errors='coerce'
)

# ============================================================
# CHECK FOR INVALID DATES
# ============================================================

print("=" * 70)
print("INVALID DATE CHECK")
print("=" * 70)

print("\nSales invalid dates:",
      sales['Sale_Date'].isna().sum())

print("Inventory invalid dates:",
      inventory['Last_Updated'].isna().sum())

print("Purchase Order invalid order dates:",
      purchase_orders['Order_Date'].isna().sum())

print("Purchase Order invalid arrival dates:",
      purchase_orders['Arrival_Date'].isna().sum())


# ============================================================
# DATE RANGES
# ============================================================

print("\n" + "=" * 70)
print("DATE RANGES")
print("=" * 70)

print("\nSales:")
print("Start Date :", sales['Sale_Date'].min().date())
print("End Date   :", sales['Sale_Date'].max().date())

print("\nInventory:")
print("Start Date :", inventory['Last_Updated'].min().date())
print("End Date   :", inventory['Last_Updated'].max().date())

print("\nPurchase Orders:")
print("Order Start Date :", purchase_orders['Order_Date'].min().date())
print("Order End Date   :", purchase_orders['Order_Date'].max().date())

print("Arrival Start Date :", purchase_orders['Arrival_Date'].min().date())
print("Arrival End Date   :", purchase_orders['Arrival_Date'].max().date())


# ============================================================
# DATE TYPES AFTER CONVERSION
# ============================================================

print("\n" + "=" * 70)
print("DATE DATA TYPES AFTER CONVERSION")
print("=" * 70)

print("\nSales:", sales['Sale_Date'].dtype)
print("Inventory:", inventory['Last_Updated'].dtype)
print("PO Order Date:", purchase_orders['Order_Date'].dtype)
print("PO Arrival Date:", purchase_orders['Arrival_Date'].dtype)

======================================================================
INVALID DATE CHECK
======================================================================

Sales invalid dates: 0
Inventory invalid dates: 0
Purchase Order invalid order dates: 0
Purchase Order invalid arrival dates: 0

======================================================================
DATE RANGES
======================================================================

Sales:
Start Date : 2024-01-01
End Date   : 2037-09-08

Inventory:
Start Date : 2024-02-01
End Date   : 2024-08-18

Purchase Orders:
Order Start Date : 2024-01-01
Order End Date   : 2026-09-26
Arrival Start Date : 2024-01-06
Arrival End Date   : 2026-10-01

======================================================================
DATE DATA TYPES AFTER CONVERSION
======================================================================

Sales: datetime64[ns]
Inventory: datetime64[ns]
PO Order Date: datetime64[ns]
PO Arrival Date: datetime64[ns]

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 4: PRIMARY KEY & FOREIGN KEY VALIDATION
# ============================================================

print("=" * 70)
print("PRIMARY KEY VALIDATION")
print("=" * 70)

# ------------------------------------------------------------
# Primary Key / Unique ID checks
# ------------------------------------------------------------

print("\nSALES - Sale_ID")
print("Total rows:", len(sales))
print("Unique Sale_ID:", sales['Sale_ID'].nunique())
print("Duplicate Sale_ID:", sales['Sale_ID'].duplicated().sum())

print("\nPURCHASE ORDERS - Order_ID")
print("Total rows:", len(purchase_orders))
print("Unique Order_ID:", purchase_orders['Order_ID'].nunique())
print("Duplicate Order_ID:", purchase_orders['Order_ID'].duplicated().sum())

print("\nSUPPLIERS - Supplier_ID")
print("Total rows:", len(suppliers))
print("Unique Supplier_ID:", suppliers['Supplier_ID'].nunique())
print("Duplicate Supplier_ID:", suppliers['Supplier_ID'].duplicated().sum())


# ============================================================
# FOREIGN KEY VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("FOREIGN KEY VALIDATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Product IDs
# ------------------------------------------------------------

sales_products = set(sales['Product_ID'])
inventory_products = set(inventory['Product_ID'])
supplier_products = set(suppliers['Product_ID'])
po_products = set(purchase_orders['Product_ID'])

all_products = sorted(
    sales_products |
    inventory_products |
    supplier_products |
    po_products
)

print("\nPRODUCT_ID VALIDATION")

for product in all_products:
    print(
        product,
        "| Sales:", product in sales_products,
        "| Inventory:", product in inventory_products,
        "| Suppliers:", product in supplier_products,
        "| Purchase Orders:", product in po_products
    )


# ------------------------------------------------------------
# 2. Store IDs
# ------------------------------------------------------------

sales_stores = set(sales['Store_ID'])
inventory_stores = set(inventory['Store_ID'])

print("\nSTORE_ID VALIDATION")

print("Sales Stores:", sorted(sales_stores))
print("Inventory Stores:", sorted(inventory_stores))

print(
    "Stores in Sales but not Inventory:",
    sorted(sales_stores - inventory_stores)
)

print(
    "Stores in Inventory but not Sales:",
    sorted(inventory_stores - sales_stores)
)


# ------------------------------------------------------------
# 3. Supplier IDs
# ------------------------------------------------------------

supplier_ids = set(suppliers['Supplier_ID'])
po_supplier_ids = set(purchase_orders['Supplier_ID'])

print("\nSUPPLIER_ID VALIDATION")

print("Suppliers in Supplier table:", len(supplier_ids))
print("Suppliers in Purchase Orders:", len(po_supplier_ids))

print(
    "PO Supplier IDs missing from Supplier table:",
    sorted(po_supplier_ids - supplier_ids)
)

print(
    "Supplier IDs not used in Purchase Orders:",
    sorted(supplier_ids - po_supplier_ids)
)


# ============================================================
# SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("VALIDATION SUMMARY")
print("=" * 70)

print("\nSales Product IDs not in Inventory:",
      sorted(sales_products - inventory_products))

print("Inventory Product IDs not in Sales:",
      sorted(inventory_products - sales_products))

print("Sales Product IDs not in Suppliers:",
      sorted(sales_products - supplier_products))

print("PO Product IDs not in Suppliers:",
      sorted(po_products - supplier_products))

print("PO Supplier IDs not in Supplier Master:",
      sorted(po_supplier_ids - supplier_ids))

======================================================================
PRIMARY KEY VALIDATION
======================================================================

SALES - Sale_ID
Total rows: 5000
Unique Sale_ID: 5000
Duplicate Sale_ID: 0

PURCHASE ORDERS - Order_ID
Total rows: 1000
Unique Order_ID: 1000
Duplicate Order_ID: 0

SUPPLIERS - Supplier_ID
Total rows: 50
Unique Supplier_ID: 50
Duplicate Supplier_ID: 0

======================================================================
FOREIGN KEY VALIDATION
======================================================================

PRODUCT_ID VALIDATION
P001 | Sales: True | Inventory: True | Suppliers: True | Purchase Orders: True
P002 | Sales: True | Inventory: True | Suppliers: True | Purchase Orders: True
P003 | Sales: True | Inventory: True | Suppliers: True | Purchase Orders: True
P004 | Sales: True | Inventory: True | Suppliers: True | Purchase Orders: True
P005 | Sales: True | Inventory: True | Suppliers: True | Purchase Orders: True

STORE_ID VALIDATION
Sales Stores: ['S101', 'S102', 'S103', 'S104']
Inventory Stores: ['S101', 'S102', 'S103', 'S104']
Stores in Sales but not Inventory: []
Stores in Inventory but not Sales: []

SUPPLIER_ID VALIDATION
Suppliers in Supplier table: 50
Suppliers in Purchase Orders: 50
PO Supplier IDs missing from Supplier table: []
Supplier IDs not used in Purchase Orders: []

======================================================================
VALIDATION SUMMARY
======================================================================

Sales Product IDs not in Inventory: []
Inventory Product IDs not in Sales: []
Sales Product IDs not in Suppliers: []
PO Product IDs not in Suppliers: []
PO Supplier IDs not in Supplier Master: []

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 5: SALES ANALYSIS
# ============================================================

print("=" * 70)
print("SALES ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Overall Sales KPIs
# ------------------------------------------------------------

total_transactions = len(sales)
total_quantity = sales['Quantity_Sold'].sum()
total_revenue = sales['Revenue'].sum()
average_transaction_quantity = sales['Quantity_Sold'].mean()
average_transaction_revenue = sales['Revenue'].mean()

print("\nOVERALL SALES KPIs")
print("-" * 50)

print(f"Total Transactions       : {total_transactions:,}")
print(f"Total Quantity Sold      : {total_quantity:,}")
print(f"Total Revenue            : {total_revenue:,.2f}")
print(f"Avg Quantity / Transaction : {average_transaction_quantity:,.2f}")
print(f"Avg Revenue / Transaction  : {average_transaction_revenue:,.2f}")


# ------------------------------------------------------------
# 2. Product-Level Sales
# ------------------------------------------------------------

product_sales = (
    sales.groupby('Product_ID')
    .agg(
        Transactions=('Sale_ID', 'count'),
        Quantity_Sold=('Quantity_Sold', 'sum'),
        Revenue=('Revenue', 'sum')
    )
    .reset_index()
)

product_sales['Revenue_Per_Unit'] = (
    product_sales['Revenue'] /
    product_sales['Quantity_Sold']
)

product_sales = product_sales.sort_values(
    'Quantity_Sold',
    ascending=False
)

print("\n" + "=" * 70)
print("PRODUCT-LEVEL SALES")
print("=" * 70)

display(product_sales)


# ------------------------------------------------------------
# 3. Store-Level Sales
# ------------------------------------------------------------

store_sales = (
    sales.groupby('Store_ID')
    .agg(
        Transactions=('Sale_ID', 'count'),
        Quantity_Sold=('Quantity_Sold', 'sum'),
        Revenue=('Revenue', 'sum')
    )
    .reset_index()
)

store_sales = store_sales.sort_values(
    'Revenue',
    ascending=False
)

print("\n" + "=" * 70)
print("STORE-LEVEL SALES")
print("=" * 70)

display(store_sales)


# ------------------------------------------------------------
# 4. Monthly Sales
# ------------------------------------------------------------

sales['Year_Month'] = sales['Sale_Date'].dt.to_period('M').astype(str)

monthly_sales = (
    sales.groupby('Year_Month')
    .agg(
        Transactions=('Sale_ID', 'count'),
        Quantity_Sold=('Quantity_Sold', 'sum'),
        Revenue=('Revenue', 'sum')
    )
    .reset_index()
)

monthly_sales = monthly_sales.sort_values('Year_Month')

print("\n" + "=" * 70)
print("MONTHLY SALES")
print("=" * 70)

display(monthly_sales)


# ------------------------------------------------------------
# 5. Fastest & Slowest Products
# ------------------------------------------------------------

fastest_product = product_sales.iloc[0]
slowest_product = product_sales.iloc[-1]

print("\n" + "=" * 70)
print("FASTEST & SLOWEST MOVING PRODUCTS")
print("=" * 70)

print(
    f"\nFastest-moving product by quantity: "
    f"{fastest_product['Product_ID']} "
    f"({fastest_product['Quantity_Sold']:,} units)"
)

print(
    f"Slowest-moving product by quantity: "
    f"{slowest_product['Product_ID']} "
    f"({slowest_product['Quantity_Sold']:,} units)"
)

======================================================================
SALES ANALYSIS
======================================================================

OVERALL SALES KPIs
--------------------------------------------------
Total Transactions       : 5,000
Total Quantity Sold      : 1,292,122
Total Revenue            : 125,870,014.00
Avg Quantity / Transaction : 258.42
Avg Revenue / Transaction  : 25,174.00

======================================================================
PRODUCT-LEVEL SALES
======================================================================

  Product_ID  Transactions  Quantity_Sold   Revenue  Revenue_Per_Unit
1       P002          1018         269100  26084882         96.933787
0       P001          1044         260296  25355109         97.408754
3       P004           985         258635  24835649         96.025863
4       P005           973         254794  24896449         97.712069
2       P003           980         249297  24697925         99.070286

======================================================================
STORE-LEVEL SALES
======================================================================

  Store_ID  Transactions  Quantity_Sold   Revenue
3     S104          1287         327280  32768228
0     S101          1256         332137  31761400
1     S102          1247         323034  31510759
2     S103          1210         309671  29829627

======================================================================
MONTHLY SALES
======================================================================

    Year_Month  Transactions  Quantity_Sold  Revenue
0      2024-01            31           8623   706316
1      2024-02            29           7334   748910
2      2024-03            31           7327   749353
3      2024-04            30           8389   770649
4      2024-05            31           8277   793790
..         ...           ...            ...      ...
160    2037-05            31           8826   734901
161    2037-06            30           7585   664893
162    2037-07            31           6738   696360
163    2037-08            31           8385   850017
164    2037-09             8           1782   287878

[165 rows x 4 columns]

======================================================================
FASTEST & SLOWEST MOVING PRODUCTS
======================================================================

Fastest-moving product by quantity: P002 (269,100 units)
Slowest-moving product by quantity: P003 (249,297 units)

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 6: INVENTORY ANALYSIS
# ============================================================

print("=" * 70)
print("INVENTORY ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Create Inventory Metrics
# ------------------------------------------------------------

inventory['Stock_Gap'] = (
    inventory['Stock_Level'] -
    inventory['Reorder_Level']
)

inventory['Stock_to_Reorder_Ratio'] = (
    inventory['Stock_Level'] /
    inventory['Reorder_Level']
)

# Inventory status
inventory['Stock_Status'] = np.select(
    [
        inventory['Stock_Level'] < inventory['Reorder_Level'],
        inventory['Stock_Level'] == inventory['Reorder_Level'],
        inventory['Stock_Level'] > inventory['Reorder_Level']
    ],
    [
        'Below Reorder Level',
        'At Reorder Level',
        'Above Reorder Level'
    ],
    default='Unknown'
)


# ------------------------------------------------------------
# 2. Overall Inventory KPIs
# ------------------------------------------------------------

total_inventory_records = len(inventory)

below_reorder = (
    inventory['Stock_Status'] == 'Below Reorder Level'
).sum()

at_reorder = (
    inventory['Stock_Status'] == 'At Reorder Level'
).sum()

above_reorder = (
    inventory['Stock_Status'] == 'Above Reorder Level'
).sum()

reorder_risk_pct = (
    below_reorder / total_inventory_records
) * 100

print("\nOVERALL INVENTORY KPIs")
print("-" * 50)

print(f"Total Inventory Records : {total_inventory_records}")
print(f"Below Reorder Level     : {below_reorder}")
print(f"At Reorder Level        : {at_reorder}")
print(f"Above Reorder Level     : {above_reorder}")
print(f"Reorder Risk %          : {reorder_risk_pct:.2f}%")


# ------------------------------------------------------------
# 3. Inventory Status Distribution
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INVENTORY STATUS DISTRIBUTION")
print("=" * 70)

status_summary = (
    inventory['Stock_Status']
    .value_counts()
    .reset_index()
)

status_summary.columns = [
    'Stock_Status',
    'Records'
]

status_summary['Percentage'] = (
    status_summary['Records'] /
    total_inventory_records
) * 100

display(status_summary)


# ------------------------------------------------------------
# 4. Product-Level Inventory Analysis
# ------------------------------------------------------------

product_inventory = (
    inventory.groupby('Product_ID')
    .agg(
        Inventory_Records=('Product_ID', 'count'),
        Total_Stock=('Stock_Level', 'sum'),
        Average_Stock=('Stock_Level', 'mean'),
        Total_Reorder_Level=('Reorder_Level', 'sum'),
        Average_Reorder_Level=('Reorder_Level', 'mean'),
        Below_Reorder_Count=(
            'Stock_Status',
            lambda x: (x == 'Below Reorder Level').sum()
        )
    )
    .reset_index()
)

product_inventory['Stock_Gap'] = (
    product_inventory['Total_Stock'] -
    product_inventory['Total_Reorder_Level']
)

product_inventory['Reorder_Risk_%'] = (
    product_inventory['Below_Reorder_Count'] /
    product_inventory['Inventory_Records']
) * 100

product_inventory = product_inventory.sort_values(
    'Below_Reorder_Count',
    ascending=False
)

print("\n" + "=" * 70)
print("PRODUCT-LEVEL INVENTORY ANALYSIS")
print("=" * 70)

display(product_inventory)


# ------------------------------------------------------------
# 5. Store-Level Inventory Analysis
# ------------------------------------------------------------

store_inventory = (
    inventory.groupby('Store_ID')
    .agg(
        Inventory_Records=('Product_ID', 'count'),
        Total_Stock=('Stock_Level', 'sum'),
        Average_Stock=('Stock_Level', 'mean'),
        Total_Reorder_Level=('Reorder_Level', 'sum'),
        Below_Reorder_Count=(
            'Stock_Status',
            lambda x: (x == 'Below Reorder Level').sum()
        )
    )
    .reset_index()
)

store_inventory['Reorder_Risk_%'] = (
    store_inventory['Below_Reorder_Count'] /
    store_inventory['Inventory_Records']
) * 100

store_inventory = store_inventory.sort_values(
    'Below_Reorder_Count',
    ascending=False
)

print("\n" + "=" * 70)
print("STORE-LEVEL INVENTORY ANALYSIS")
print("=" * 70)

display(store_inventory)


# ------------------------------------------------------------
# 6. Critical Inventory Records
# ------------------------------------------------------------

critical_inventory = inventory[
    inventory['Stock_Status'] == 'Below Reorder Level'
].sort_values(
    'Stock_Gap'
)

print("\n" + "=" * 70)
print("CRITICAL INVENTORY RECORDS")
print("=" * 70)

display(
    critical_inventory[
        [
            'Product_ID',
            'Store_ID',
            'Warehouse_ID',
            'Stock_Level',
            'Reorder_Level',
            'Stock_Gap',
            'Stock_to_Reorder_Ratio',
            'Last_Updated'
        ]
    ].head(20)
)

======================================================================
INVENTORY ANALYSIS
======================================================================

OVERALL INVENTORY KPIs
--------------------------------------------------
Total Inventory Records : 200
Below Reorder Level     : 53
At Reorder Level        : 1
Above Reorder Level     : 146
Reorder Risk %          : 26.50%

======================================================================
INVENTORY STATUS DISTRIBUTION
======================================================================

          Stock_Status  Records  Percentage
0  Above Reorder Level      146        73.0
1  Below Reorder Level       53        26.5
2     At Reorder Level        1         0.5

======================================================================
PRODUCT-LEVEL INVENTORY ANALYSIS
======================================================================

,Product_ID,Inventory_Records,Total_Stock,Average_Stock,Total_Reorder_Level,Average_Reorder_Level,Below_Reorder_Count,Stock_Gap,Reorder_Risk_%
2,P003,51,11481,225.117647,6538,128.196078,14,4943,27.450980
3,P004,36,7980,221.666667,4336,120.444444,12,3644,33.333333
0,P001,40,9249,231.225000,5280,132.000000,10,3969,25.000000
4,P005,34,6640,195.294118,4006,117.823529,9,2634,26.470588
1,P002,39,9641,247.205128,4798,123.025641,8,4843,20.512821

======================================================================
STORE-LEVEL INVENTORY ANALYSIS
======================================================================

,Store_ID,Inventory_Records,Total_Stock,Average_Stock,Total_Reorder_Level,Below_Reorder_Count,Reorder_Risk_%
0,S101,59,12248,207.593220,7590,19,32.203390
1,S102,48,11678,243.291667,6235,16,33.333333
2,S103,53,11768,222.037736,6007,9,16.981132
3,S104,40,9297,232.425000,5126,9,22.500000

======================================================================
CRITICAL INVENTORY RECORDS
======================================================================

,Product_ID,Store_ID,Warehouse_ID,Stock_Level,Reorder_Level,Stock_Gap,Stock_to_Reorder_Ratio,Last_Updated
122,P005,S104,W003,11,194,-183,0.056701,2024-06-02
1,P004,S103,W003,24,178,-154,0.134831,2024-02-02
107,P004,S103,W002,18,148,-130,0.121622,2024-05-18
89,P004,S102,W003,41,165,-124,0.248485,2024-04-30
97,P004,S101,W001,43,165,-122,0.260606,2024-05-08
64,P001,S101,W003,72,192,-120,0.375000,2024-04-05
187,P003,S102,W003,49,168,-119,0.291667,2024-08-06
164,P003,S101,W002,52,166,-114,0.313253,2024-07-14
20,P005,S104,W003,52,162,-110,0.320988,2024-02-21
13,P004,S101,W002,87,190,-103,0.457895,2024-02-14
36,P003,S102,W001,93,194,-101,0.479381,2024-03-08
78,P001,S102,W002,74,173,-99,0.427746,2024-04-19
102,P003,S102,W001,79,178,-99,0.443820,2024-05-13
4,P002,S101,W002,57,155,-98,0.367742,2024-02-05
62,P001,S102,W001,59,154,-95,0.383117,2024-04-03
70,P001,S101,W002,74,168,-94,0.440476,2024-04-11
3,P003,S101,W003,61,148,-87,0.412162,2024-02-04
117,P001,S103,W002,34,118,-84,0.288136,2024-05-28
43,P005,S103,W001,55,134,-79,0.410448,2024-03-15
112,P003,S104,W003,70,148,-78,0.472973,2024-05-23

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 7: SALES + INVENTORY COMBINED ANALYSIS
# ============================================================

print("=" * 70)
print("SALES + INVENTORY COMBINED ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Product-Level Sales Summary
# ------------------------------------------------------------

product_demand = (
    sales.groupby('Product_ID')
    .agg(
        Transactions=('Sale_ID', 'count'),
        Total_Quantity_Sold=('Quantity_Sold', 'sum'),
        Total_Revenue=('Revenue', 'sum'),
        Average_Quantity_Per_Transaction=('Quantity_Sold', 'mean')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 2. Product-Level Inventory Summary
# ------------------------------------------------------------

product_stock = (
    inventory.groupby('Product_ID')
    .agg(
        Inventory_Records=('Product_ID', 'count'),
        Total_Stock=('Stock_Level', 'sum'),
        Average_Stock=('Stock_Level', 'mean'),
        Total_Reorder_Level=('Reorder_Level', 'sum'),
        Below_Reorder_Count=(
            'Stock_Status',
            lambda x: (x == 'Below Reorder Level').sum()
        )
    )
    .reset_index()
)


# ------------------------------------------------------------
# 3. Merge Sales + Inventory
# ------------------------------------------------------------

product_analysis = pd.merge(
    product_demand,
    product_stock,
    on='Product_ID',
    how='inner'
)


# ------------------------------------------------------------
# 4. Derived Metrics
# ------------------------------------------------------------

product_analysis['Stock_Gap'] = (
    product_analysis['Total_Stock'] -
    product_analysis['Total_Reorder_Level']
)

product_analysis['Reorder_Risk_%'] = (
    product_analysis['Below_Reorder_Count'] /
    product_analysis['Inventory_Records']
) * 100

# Average quantity sold per transaction
product_analysis['Avg_Demand_Per_Transaction'] = (
    product_analysis['Total_Quantity_Sold'] /
    product_analysis['Transactions']
)

# Approximate stock-to-demand ratio
product_analysis['Stock_to_Demand_Ratio'] = (
    product_analysis['Total_Stock'] /
    product_analysis['Total_Quantity_Sold']
)

# Inventory coverage proxy
product_analysis['Demand_per_Inventory_Record'] = (
    product_analysis['Total_Quantity_Sold'] /
    product_analysis['Inventory_Records']
)


# ------------------------------------------------------------
# 5. Demand Classification
# ------------------------------------------------------------

median_demand = product_analysis['Total_Quantity_Sold'].median()

product_analysis['Demand_Category'] = np.where(
    product_analysis['Total_Quantity_Sold'] >= median_demand,
    'High Demand',
    'Low Demand'
)


# ------------------------------------------------------------
# 6. Inventory Risk Classification
# ------------------------------------------------------------

product_analysis['Inventory_Risk'] = np.select(
    [
        product_analysis['Reorder_Risk_%'] >= 30,
        product_analysis['Reorder_Risk_%'] >= 20,
        product_analysis['Reorder_Risk_%'] < 20
    ],
    [
        'High Risk',
        'Medium Risk',
        'Low Risk'
    ],
    default='Unknown'
)


# ------------------------------------------------------------
# 7. Combined Business Classification
# ------------------------------------------------------------

product_analysis['Supply_Chain_Category'] = np.select(
    [
        (product_analysis['Demand_Category'] == 'High Demand') &
        (product_analysis['Inventory_Risk'] == 'High Risk'),

        (product_analysis['Demand_Category'] == 'High Demand') &
        (product_analysis['Inventory_Risk'] != 'High Risk'),

        (product_analysis['Demand_Category'] == 'Low Demand') &
        (product_analysis['Inventory_Risk'] == 'High Risk'),

        (product_analysis['Demand_Category'] == 'Low Demand') &
        (product_analysis['Inventory_Risk'] != 'High Risk')
    ],
    [
        'High Demand - High Inventory Risk',
        'High Demand - Lower Inventory Risk',
        'Low Demand - High Inventory Risk',
        'Low Demand - Lower Inventory Risk'
    ],
    default='Unclassified'
)


# ------------------------------------------------------------
# 8. Display Combined Analysis
# ------------------------------------------------------------

product_analysis = product_analysis.sort_values(
    ['Inventory_Risk', 'Total_Quantity_Sold'],
    ascending=[True, False]
)

print("\nPRODUCT-LEVEL SALES + INVENTORY ANALYSIS")
print("=" * 70)

display(product_analysis)


# ------------------------------------------------------------
# 9. Most Critical Products
# ------------------------------------------------------------

critical_products = product_analysis.sort_values(
    ['Below_Reorder_Count', 'Reorder_Risk_%'],
    ascending=[False, False]
)

print("\n" + "=" * 70)
print("PRODUCTS WITH HIGHEST REORDER RISK")
print("=" * 70)

display(
    critical_products[
        [
            'Product_ID',
            'Total_Quantity_Sold',
            'Total_Revenue',
            'Total_Stock',
            'Total_Reorder_Level',
            'Below_Reorder_Count',
            'Reorder_Risk_%',
            'Demand_Category',
            'Inventory_Risk',
            'Supply_Chain_Category'
        ]
    ]
)


# ------------------------------------------------------------
# 10. High Demand + High Risk Products
# ------------------------------------------------------------

high_risk_demand = product_analysis[
    product_analysis['Supply_Chain_Category'] ==
    'High Demand - High Inventory Risk'
]

print("\n" + "=" * 70)
print("HIGH DEMAND + HIGH INVENTORY RISK")
print("=" * 70)

display(high_risk_demand)

======================================================================
SALES + INVENTORY COMBINED ANALYSIS
======================================================================

PRODUCT-LEVEL SALES + INVENTORY ANALYSIS
======================================================================

,Product_ID,Transactions,Total_Quantity_Sold,Total_Revenue,Average_Quantity_Per_Transaction,Inventory_Records,Total_Stock,Average_Stock,Total_Reorder_Level,Below_Reorder_Count,Stock_Gap,Reorder_Risk_%,Avg_Demand_Per_Transaction,Stock_to_Demand_Ratio,Demand_per_Inventory_Record,Demand_Category,Inventory_Risk,Supply_Chain_Category
3,P004,985,258635,24835649,262.573604,36,7980,221.666667,4336,12,3644,33.333333,262.573604,0.030854,7184.305556,High Demand,High Risk,High Demand - High Inventory Risk
1,P002,1018,269100,26084882,264.341847,39,9641,247.205128,4798,8,4843,20.512821,264.341847,0.035827,6900.000000,High Demand,Medium Risk,High Demand - Lower Inventory Risk
0,P001,1044,260296,25355109,249.325670,40,9249,231.225000,5280,10,3969,25.000000,249.325670,0.035533,6507.400000,High Demand,Medium Risk,High Demand - Lower Inventory Risk
4,P005,973,254794,24896449,261.864337,34,6640,195.294118,4006,9,2634,26.470588,261.864337,0.026060,7493.941176,Low Demand,Medium Risk,Low Demand - Lower Inventory Risk
2,P003,980,249297,24697925,254.384694,51,11481,225.117647,6538,14,4943,27.450980,254.384694,0.046054,4888.176471,Low Demand,Medium Risk,Low Demand - Lower Inventory Risk

======================================================================
PRODUCTS WITH HIGHEST REORDER RISK
======================================================================

,Product_ID,Total_Quantity_Sold,Total_Revenue,Total_Stock,Total_Reorder_Level,Below_Reorder_Count,Reorder_Risk_%,Demand_Category,Inventory_Risk,Supply_Chain_Category
2,P003,249297,24697925,11481,6538,14,27.450980,Low Demand,Medium Risk,Low Demand - Lower Inventory Risk
3,P004,258635,24835649,7980,4336,12,33.333333,High Demand,High Risk,High Demand - High Inventory Risk
0,P001,260296,25355109,9249,5280,10,25.000000,High Demand,Medium Risk,High Demand - Lower Inventory Risk
4,P005,254794,24896449,6640,4006,9,26.470588,Low Demand,Medium Risk,Low Demand - Lower Inventory Risk
1,P002,269100,26084882,9641,4798,8,20.512821,High Demand,Medium Risk,High Demand - Lower Inventory Risk

======================================================================
HIGH DEMAND + HIGH INVENTORY RISK
======================================================================

,Product_ID,Transactions,Total_Quantity_Sold,Total_Revenue,Average_Quantity_Per_Transaction,Inventory_Records,Total_Stock,Average_Stock,Total_Reorder_Level,Below_Reorder_Count,Stock_Gap,Reorder_Risk_%,Avg_Demand_Per_Transaction,Stock_to_Demand_Ratio,Demand_per_Inventory_Record,Demand_Category,Inventory_Risk,Supply_Chain_Category
3,P004,985,258635,24835649,262.573604,36,7980,221.666667,4336,12,3644,33.333333,262.573604,0.030854,7184.305556,High Demand,High Risk,High Demand - High Inventory Risk

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 8: PURCHASE ORDER & SUPPLIER LEAD-TIME ANALYSIS
# ============================================================

print("=" * 70)
print("PURCHASE ORDER & SUPPLIER LEAD-TIME ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Calculate Actual Supplier Lead Time
# ------------------------------------------------------------

purchase_orders['Actual_Lead_Time_Days'] = (
    purchase_orders['Arrival_Date'] -
    purchase_orders['Order_Date']
).dt.days


# ------------------------------------------------------------
# 2. Validate Lead-Time Values
# ------------------------------------------------------------

print("\nACTUAL LEAD-TIME SUMMARY")
print("-" * 70)

print(
    purchase_orders['Actual_Lead_Time_Days'].describe()
)


# ------------------------------------------------------------
# 3. Check for Invalid Lead Times
# ------------------------------------------------------------

invalid_lead_time = purchase_orders[
    purchase_orders['Actual_Lead_Time_Days'] < 0
]

print("\nInvalid / Negative Lead-Time Records:",
      len(invalid_lead_time))


# ------------------------------------------------------------
# 4. Purchase Order KPIs
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PURCHASE ORDER KPIs")
print("=" * 70)

print(f"Total Purchase Orders        : {len(purchase_orders):,}")
print(f"Total Quantity Ordered       : {purchase_orders['Quantity'].sum():,}")
print(
    f"Average Order Quantity       : "
    f"{purchase_orders['Quantity'].mean():,.2f}"
)
print(
    f"Average Actual Lead Time    : "
    f"{purchase_orders['Actual_Lead_Time_Days'].mean():.2f} days"
)
print(
    f"Minimum Actual Lead Time    : "
    f"{purchase_orders['Actual_Lead_Time_Days'].min()} days"
)
print(
    f"Maximum Actual Lead Time    : "
    f"{purchase_orders['Actual_Lead_Time_Days'].max()} days"
)


# ------------------------------------------------------------
# 5. Supplier-Level Analysis
# ------------------------------------------------------------

supplier_po_analysis = (
    purchase_orders
    .groupby('Supplier_ID')
    .agg(
        Purchase_Orders=('Order_ID', 'count'),
        Total_Quantity_Ordered=('Quantity', 'sum'),
        Average_Order_Quantity=('Quantity', 'mean'),
        Average_Actual_Lead_Time=('Actual_Lead_Time_Days', 'mean'),
        Minimum_Actual_Lead_Time=('Actual_Lead_Time_Days', 'min'),
        Maximum_Actual_Lead_Time=('Actual_Lead_Time_Days', 'max')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 6. Merge Supplier Master Information
# ------------------------------------------------------------

supplier_master = suppliers[
    [
        'Supplier_ID',
        'Supplier_Name',
        'Product_ID',
        'Lead_Time (days)',
        'Order_Frequency'
    ]
].copy()

supplier_analysis = pd.merge(
    supplier_master,
    supplier_po_analysis,
    on='Supplier_ID',
    how='left'
)


# ------------------------------------------------------------
# 7. Lead-Time Difference
# ------------------------------------------------------------

supplier_analysis['Lead_Time_Difference'] = (
    supplier_analysis['Average_Actual_Lead_Time'] -
    supplier_analysis['Lead_Time (days)']
)


# ------------------------------------------------------------
# 8. Supplier Analysis Output
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SUPPLIER-LEVEL ANALYSIS")
print("=" * 70)

display(
    supplier_analysis.sort_values(
        'Average_Actual_Lead_Time',
        ascending=False
    )
)


# ------------------------------------------------------------
# 9. Supplier Lead-Time Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LEAD-TIME SUMMARY BY SUPPLIER")
print("=" * 70)

display(
    supplier_analysis[
        [
            'Supplier_ID',
            'Supplier_Name',
            'Product_ID',
            'Lead_Time (days)',
            'Order_Frequency',
            'Purchase_Orders',
            'Total_Quantity_Ordered',
            'Average_Actual_Lead_Time',
            'Minimum_Actual_Lead_Time',
            'Maximum_Actual_Lead_Time',
            'Lead_Time_Difference'
        ]
    ]
    .sort_values(
        'Average_Actual_Lead_Time',
        ascending=False
    )
)


# ------------------------------------------------------------
# 10. Lead-Time Distribution
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("ACTUAL LEAD-TIME DISTRIBUTION")
print("=" * 70)

lead_time_distribution = (
    purchase_orders['Actual_Lead_Time_Days']
    .value_counts()
    .sort_index()
    .reset_index()
)

lead_time_distribution.columns = [
    'Actual_Lead_Time_Days',
    'Purchase_Order_Count'
]

display(lead_time_distribution)


# ------------------------------------------------------------
# 11. Supplier Order Frequency Distribution
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SUPPLIER ORDER FREQUENCY DISTRIBUTION")
print("=" * 70)

display(
    suppliers['Order_Frequency']
    .value_counts()
    .reset_index()
)


# ------------------------------------------------------------
# 12. Product-Level Procurement Analysis
# ------------------------------------------------------------

product_procurement = (
    purchase_orders
    .groupby('Product_ID')
    .agg(
        Purchase_Orders=('Order_ID', 'count'),
        Total_Quantity_Ordered=('Quantity', 'sum'),
        Average_Order_Quantity=('Quantity', 'mean'),
        Average_Actual_Lead_Time=('Actual_Lead_Time_Days', 'mean')
    )
    .reset_index()
)

print("\n" + "=" * 70)
print("PRODUCT-LEVEL PROCUREMENT ANALYSIS")
print("=" * 70)

display(
    product_procurement.sort_values(
        'Total_Quantity_Ordered',
        ascending=False
    )
)

======================================================================
PURCHASE ORDER & SUPPLIER LEAD-TIME ANALYSIS
======================================================================

ACTUAL LEAD-TIME SUMMARY
----------------------------------------------------------------------
count    1000.0
mean        5.0
std         0.0
min         5.0
25%         5.0
50%         5.0
75%         5.0
max         5.0
Name: Actual_Lead_Time_Days, dtype: float64

Invalid / Negative Lead-Time Records: 0

======================================================================
PURCHASE ORDER KPIs
======================================================================
Total Purchase Orders        : 1,000
Total Quantity Ordered       : 276,488
Average Order Quantity       : 276.49
Average Actual Lead Time    : 5.00 days
Minimum Actual Lead Time    : 5 days
Maximum Actual Lead Time    : 5 days

======================================================================
SUPPLIER-LEVEL ANALYSIS
======================================================================

,Supplier_ID,Supplier_Name,Product_ID,Lead_Time (days),Order_Frequency,Purchase_Orders,Total_Quantity_Ordered,Average_Order_Quantity,Average_Actual_Lead_Time,Minimum_Actual_Lead_Time,Maximum_Actual_Lead_Time,Lead_Time_Difference
0,SUP001,Murray-Ramirez,P002,9,Weekly,18,5328,296.000000,5.0,5,5,-4.0
1,SUP002,"Thomas, Meyer and Campbell",P005,9,Weekly,21,6016,286.476190,5.0,5,5,-4.0
2,SUP003,Acosta Inc,P005,4,Monthly,22,5521,250.954545,5.0,5,5,1.0
3,SUP004,"Evans, Brown and Turner",P002,8,Weekly,25,6927,277.080000,5.0,5,5,-3.0
4,SUP005,"Johnson, Wise and Barr",P003,6,Biweekly,27,7981,295.592593,5.0,5,5,-1.0
5,SUP006,"Hood, Barrera and Woodard",P001,6,Monthly,14,4498,321.285714,5.0,5,5,-1.0
6,SUP007,"Meyers, Miller and Young",P002,9,Weekly,19,5620,295.789474,5.0,5,5,-4.0
7,SUP008,Edwards-Barnes,P005,8,Weekly,33,9350,283.333333,5.0,5,5,-3.0
8,SUP009,Baker LLC,P001,4,Weekly,15,3780,252.000000,5.0,5,5,1.0
9,SUP010,Wright PLC,P003,9,Monthly,20,6451,322.550000,5.0,5,5,-4.0
10,SUP011,"Peterson, Thomas and Page",P004,4,Biweekly,27,7267,269.148148,5.0,5,5,1.0
11,SUP012,"Wright, White and Gonzalez",P004,6,Monthly,20,6159,307.950000,5.0,5,5,-1.0
12,SUP013,"Norman, Welch and Foster",P004,7,Biweekly,16,4369,273.062500,5.0,5,5,-2.0
13,SUP014,Brown LLC,P001,7,Biweekly,25,7593,303.720000,5.0,5,5,-2.0
14,SUP015,Watson Ltd,P002,4,Biweekly,16,4556,284.750000,5.0,5,5,1.0
15,SUP016,Johnson Group,P002,8,Biweekly,21,6039,287.571429,5.0,5,5,-3.0
16,SUP017,Ayers Ltd,P005,7,Monthly,19,4690,246.842105,5.0,5,5,-2.0
17,SUP018,Wilson Inc,P005,5,Weekly,19,4496,236.631579,5.0,5,5,0.0
18,SUP019,Bowers and Sons,P003,4,Weekly,20,5098,254.900000,5.0,5,5,1.0
19,SUP020,"Porter, Daniels and Stewart",P003,6,Monthly,18,4279,237.722222,5.0,5,5,-1.0
20,SUP021,Robertson LLC,P001,4,Biweekly,19,5274,277.578947,5.0,5,5,1.0
21,SUP022,"Alvarado, Ramirez and Taylor",P001,4,Biweekly,17,4523,266.058824,5.0,5,5,1.0
22,SUP023,Smith and Sons,P002,6,Monthly,19,6019,316.789474,5.0,5,5,-1.0
23,SUP024,Thompson-Hebert,P001,4,Biweekly,19,5075,267.105263,5.0,5,5,1.0
24,SUP025,Rose Inc,P005,5,Monthly,21,6333,301.571429,5.0,5,5,0.0
25,SUP026,Roberts-Williams,P005,6,Weekly,20,4965,248.250000,5.0,5,5,-1.0
26,SUP027,Woods PLC,P002,5,Monthly,18,4674,259.666667,5.0,5,5,0.0
27,SUP028,Taylor Ltd,P002,3,Biweekly,23,6299,273.869565,5.0,5,5,2.0
28,SUP029,"Duncan, Davidson and Martin",P005,9,Monthly,23,6140,266.956522,5.0,5,5,-4.0
29,SUP030,"Baker, Dean and Jensen",P002,5,Biweekly,16,3319,207.437500,5.0,5,5,0.0
30,SUP031,"Harmon, Davis and Harper",P002,5,Monthly,20,5328,266.400000,5.0,5,5,0.0
31,SUP032,Ferguson Group,P005,3,Weekly,21,4668,222.285714,5.0,5,5,2.0
32,SUP033,Murphy-Wise,P001,9,Weekly,18,4586,254.777778,5.0,5,5,-4.0
33,SUP034,"James, Mullen and Cooper",P001,9,Weekly,25,7301,292.040000,5.0,5,5,-4.0
34,SUP035,Smith PLC,P001,9,Monthly,21,6165,293.571429,5.0,5,5,-4.0
35,SUP036,"Powers, Olson and Sanchez",P004,9,Weekly,10,3078,307.800000,5.0,5,5,-4.0
36,SUP037,Kerr-Palmer,P003,8,Weekly,16,4101,256.312500,5.0,5,5,-3.0
37,SUP038,"Johnson, Turner and Carpenter",P001,8,Biweekly,15,3810,254.000000,5.0,5,5,-3.0
38,SUP039,Ortega-Manning,P005,3,Monthly,22,6557,298.045455,5.0,5,5,2.0
39,SUP040,Wilson-Stanley,P005,4,Weekly,24,6311,262.958333,5.0,5,5,1.0
40,SUP041,Brown Ltd,P003,3,Weekly,14,4114,293.857143,5.0,5,5,2.0
41,SUP042,"Cross, Scott and Avery",P004,6,Weekly,13,3280,252.307692,5.0,5,5,-1.0
42,SUP043,Fox Group,P002,9,Biweekly,18,5966,331.444444,5.0,5,5,-4.0
43,SUP044,Peters-Salas,P004,4,Monthly,20,4587,229.350000,5.0,5,5,1.0
44,SUP045,Castro-Townsend,P001,7,Weekly,21,6628,315.619048,5.0,5,5,-2.0
45,SUP046,"Harris, Patterson and Harris",P002,9,Biweekly,19,5668,298.315789,5.0,5,5,-4.0
46,SUP047,Nunez-May,P001,4,Biweekly,19,4855,255.526316,5.0,5,5,1.0
47,SUP048,Williams Inc,P003,4,Biweekly,25,6899,275.960000,5.0,5,5,1.0
48,SUP049,Obrien-Jones,P005,9,Biweekly,19,5371,282.684211,5.0,5,5,-4.0
49,SUP050,"Sosa, Cain and Cummings",P003,8,Weekly,30,8576,285.866667,5.0,5,5,-3.0

======================================================================
LEAD-TIME SUMMARY BY SUPPLIER
======================================================================

,Supplier_ID,Supplier_Name,Product_ID,Lead_Time (days),Order_Frequency,Purchase_Orders,Total_Quantity_Ordered,Average_Actual_Lead_Time,Minimum_Actual_Lead_Time,Maximum_Actual_Lead_Time,Lead_Time_Difference
0,SUP001,Murray-Ramirez,P002,9,Weekly,18,5328,5.0,5,5,-4.0
1,SUP002,"Thomas, Meyer and Campbell",P005,9,Weekly,21,6016,5.0,5,5,-4.0
2,SUP003,Acosta Inc,P005,4,Monthly,22,5521,5.0,5,5,1.0
3,SUP004,"Evans, Brown and Turner",P002,8,Weekly,25,6927,5.0,5,5,-3.0
4,SUP005,"Johnson, Wise and Barr",P003,6,Biweekly,27,7981,5.0,5,5,-1.0
5,SUP006,"Hood, Barrera and Woodard",P001,6,Monthly,14,4498,5.0,5,5,-1.0
6,SUP007,"Meyers, Miller and Young",P002,9,Weekly,19,5620,5.0,5,5,-4.0
7,SUP008,Edwards-Barnes,P005,8,Weekly,33,9350,5.0,5,5,-3.0
8,SUP009,Baker LLC,P001,4,Weekly,15,3780,5.0,5,5,1.0
9,SUP010,Wright PLC,P003,9,Monthly,20,6451,5.0,5,5,-4.0
10,SUP011,"Peterson, Thomas and Page",P004,4,Biweekly,27,7267,5.0,5,5,1.0
11,SUP012,"Wright, White and Gonzalez",P004,6,Monthly,20,6159,5.0,5,5,-1.0
12,SUP013,"Norman, Welch and Foster",P004,7,Biweekly,16,4369,5.0,5,5,-2.0
13,SUP014,Brown LLC,P001,7,Biweekly,25,7593,5.0,5,5,-2.0
14,SUP015,Watson Ltd,P002,4,Biweekly,16,4556,5.0,5,5,1.0
15,SUP016,Johnson Group,P002,8,Biweekly,21,6039,5.0,5,5,-3.0
16,SUP017,Ayers Ltd,P005,7,Monthly,19,4690,5.0,5,5,-2.0
17,SUP018,Wilson Inc,P005,5,Weekly,19,4496,5.0,5,5,0.0
18,SUP019,Bowers and Sons,P003,4,Weekly,20,5098,5.0,5,5,1.0
19,SUP020,"Porter, Daniels and Stewart",P003,6,Monthly,18,4279,5.0,5,5,-1.0
20,SUP021,Robertson LLC,P001,4,Biweekly,19,5274,5.0,5,5,1.0
21,SUP022,"Alvarado, Ramirez and Taylor",P001,4,Biweekly,17,4523,5.0,5,5,1.0
22,SUP023,Smith and Sons,P002,6,Monthly,19,6019,5.0,5,5,-1.0
23,SUP024,Thompson-Hebert,P001,4,Biweekly,19,5075,5.0,5,5,1.0
24,SUP025,Rose Inc,P005,5,Monthly,21,6333,5.0,5,5,0.0
25,SUP026,Roberts-Williams,P005,6,Weekly,20,4965,5.0,5,5,-1.0
26,SUP027,Woods PLC,P002,5,Monthly,18,4674,5.0,5,5,0.0
27,SUP028,Taylor Ltd,P002,3,Biweekly,23,6299,5.0,5,5,2.0
28,SUP029,"Duncan, Davidson and Martin",P005,9,Monthly,23,6140,5.0,5,5,-4.0
29,SUP030,"Baker, Dean and Jensen",P002,5,Biweekly,16,3319,5.0,5,5,0.0
30,SUP031,"Harmon, Davis and Harper",P002,5,Monthly,20,5328,5.0,5,5,0.0
31,SUP032,Ferguson Group,P005,3,Weekly,21,4668,5.0,5,5,2.0
32,SUP033,Murphy-Wise,P001,9,Weekly,18,4586,5.0,5,5,-4.0
33,SUP034,"James, Mullen and Cooper",P001,9,Weekly,25,7301,5.0,5,5,-4.0
34,SUP035,Smith PLC,P001,9,Monthly,21,6165,5.0,5,5,-4.0
35,SUP036,"Powers, Olson and Sanchez",P004,9,Weekly,10,3078,5.0,5,5,-4.0
36,SUP037,Kerr-Palmer,P003,8,Weekly,16,4101,5.0,5,5,-3.0
37,SUP038,"Johnson, Turner and Carpenter",P001,8,Biweekly,15,3810,5.0,5,5,-3.0
38,SUP039,Ortega-Manning,P005,3,Monthly,22,6557,5.0,5,5,2.0
39,SUP040,Wilson-Stanley,P005,4,Weekly,24,6311,5.0,5,5,1.0
40,SUP041,Brown Ltd,P003,3,Weekly,14,4114,5.0,5,5,2.0
41,SUP042,"Cross, Scott and Avery",P004,6,Weekly,13,3280,5.0,5,5,-1.0
42,SUP043,Fox Group,P002,9,Biweekly,18,5966,5.0,5,5,-4.0
43,SUP044,Peters-Salas,P004,4,Monthly,20,4587,5.0,5,5,1.0
44,SUP045,Castro-Townsend,P001,7,Weekly,21,6628,5.0,5,5,-2.0
45,SUP046,"Harris, Patterson and Harris",P002,9,Biweekly,19,5668,5.0,5,5,-4.0
46,SUP047,Nunez-May,P001,4,Biweekly,19,4855,5.0,5,5,1.0
47,SUP048,Williams Inc,P003,4,Biweekly,25,6899,5.0,5,5,1.0
48,SUP049,Obrien-Jones,P005,9,Biweekly,19,5371,5.0,5,5,-4.0
49,SUP050,"Sosa, Cain and Cummings",P003,8,Weekly,30,8576,5.0,5,5,-3.0

======================================================================
ACTUAL LEAD-TIME DISTRIBUTION
======================================================================

   Actual_Lead_Time_Days  Purchase_Order_Count
0                      5                  1000

======================================================================
SUPPLIER ORDER FREQUENCY DISTRIBUTION
======================================================================

  Order_Frequency  count
0          Weekly     19
1        Biweekly     17
2         Monthly     14

======================================================================
PRODUCT-LEVEL PROCUREMENT ANALYSIS
======================================================================

,Product_ID,Purchase_Orders,Total_Quantity_Ordered,Average_Order_Quantity,Average_Actual_Lead_Time
1,P002,216,60129,278.375000,5.0
2,P003,206,58555,284.247573,5.0
3,P004,198,53433,269.863636,5.0
4,P005,186,52544,282.494624,5.0
0,P001,194,51827,267.149485,5.0

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 9: SUPPLIER CLUSTERING DATA PREPARATION
# ============================================================

print("=" * 70)
print("SUPPLIER CLUSTERING DATA PREPARATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Create Supplier Clustering Dataset
# ------------------------------------------------------------

supplier_cluster = suppliers[
    [
        'Supplier_ID',
        'Supplier_Name',
        'Product_ID',
        'Lead_Time (days)',
        'Order_Frequency'
    ]
].copy()


# ------------------------------------------------------------
# 2. Encode Order Frequency
# ------------------------------------------------------------

frequency_mapping = {
    'Weekly': 1,
    'Biweekly': 2,
    'Monthly': 3
}

supplier_cluster['Order_Frequency_Code'] = (
    supplier_cluster['Order_Frequency']
    .map(frequency_mapping)
)


# ------------------------------------------------------------
# 3. Add Purchase Order Activity
# ------------------------------------------------------------

supplier_cluster = supplier_cluster.merge(
    supplier_po_analysis[
        [
            'Supplier_ID',
            'Purchase_Orders',
            'Total_Quantity_Ordered',
            'Average_Order_Quantity'
        ]
    ],
    on='Supplier_ID',
    how='left'
)


# ------------------------------------------------------------
# 4. Check Clustering Dataset
# ------------------------------------------------------------

print("\nSUPPLIER CLUSTERING DATASET")
print("-" * 70)

display(supplier_cluster)


# ------------------------------------------------------------
# 5. Validate Missing Values
# ------------------------------------------------------------

print("\nMISSING VALUES")
print("-" * 70)

display(
    supplier_cluster.isnull().sum()
)


# ------------------------------------------------------------
# 6. Feature Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CLUSTERING FEATURE SUMMARY")
print("=" * 70)

clustering_features = [
    'Lead_Time (days)',
    'Order_Frequency_Code',
    'Purchase_Orders',
    'Total_Quantity_Ordered',
    'Average_Order_Quantity'
]

display(
    supplier_cluster[clustering_features].describe()
)


# ------------------------------------------------------------
# 7. Lead Time Distribution in Supplier Master
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SUPPLIER MASTER LEAD-TIME DISTRIBUTION")
print("=" * 70)

display(
    supplier_cluster['Lead_Time (days)']
    .value_counts()
    .sort_index()
    .reset_index()
)


# ------------------------------------------------------------
# 8. Order Frequency Encoding Distribution
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("ORDER FREQUENCY ENCODING")
print("=" * 70)

display(
    supplier_cluster[
        ['Order_Frequency', 'Order_Frequency_Code']
    ]
    .drop_duplicates()
    .sort_values('Order_Frequency_Code')
)

======================================================================
SUPPLIER CLUSTERING DATA PREPARATION
======================================================================

SUPPLIER CLUSTERING DATASET
----------------------------------------------------------------------

,Supplier_ID,Supplier_Name,Product_ID,Lead_Time (days),Order_Frequency,Order_Frequency_Code,Purchase_Orders,Total_Quantity_Ordered,Average_Order_Quantity
0,SUP001,Murray-Ramirez,P002,9,Weekly,1,18,5328,296.000000
1,SUP002,"Thomas, Meyer and Campbell",P005,9,Weekly,1,21,6016,286.476190
2,SUP003,Acosta Inc,P005,4,Monthly,3,22,5521,250.954545
3,SUP004,"Evans, Brown and Turner",P002,8,Weekly,1,25,6927,277.080000
4,SUP005,"Johnson, Wise and Barr",P003,6,Biweekly,2,27,7981,295.592593
5,SUP006,"Hood, Barrera and Woodard",P001,6,Monthly,3,14,4498,321.285714
6,SUP007,"Meyers, Miller and Young",P002,9,Weekly,1,19,5620,295.789474
7,SUP008,Edwards-Barnes,P005,8,Weekly,1,33,9350,283.333333
8,SUP009,Baker LLC,P001,4,Weekly,1,15,3780,252.000000
9,SUP010,Wright PLC,P003,9,Monthly,3,20,6451,322.550000
10,SUP011,"Peterson, Thomas and Page",P004,4,Biweekly,2,27,7267,269.148148
11,SUP012,"Wright, White and Gonzalez",P004,6,Monthly,3,20,6159,307.950000
12,SUP013,"Norman, Welch and Foster",P004,7,Biweekly,2,16,4369,273.062500
13,SUP014,Brown LLC,P001,7,Biweekly,2,25,7593,303.720000
14,SUP015,Watson Ltd,P002,4,Biweekly,2,16,4556,284.750000
15,SUP016,Johnson Group,P002,8,Biweekly,2,21,6039,287.571429
16,SUP017,Ayers Ltd,P005,7,Monthly,3,19,4690,246.842105
17,SUP018,Wilson Inc,P005,5,Weekly,1,19,4496,236.631579
18,SUP019,Bowers and Sons,P003,4,Weekly,1,20,5098,254.900000
19,SUP020,"Porter, Daniels and Stewart",P003,6,Monthly,3,18,4279,237.722222
20,SUP021,Robertson LLC,P001,4,Biweekly,2,19,5274,277.578947
21,SUP022,"Alvarado, Ramirez and Taylor",P001,4,Biweekly,2,17,4523,266.058824
22,SUP023,Smith and Sons,P002,6,Monthly,3,19,6019,316.789474
23,SUP024,Thompson-Hebert,P001,4,Biweekly,2,19,5075,267.105263
24,SUP025,Rose Inc,P005,5,Monthly,3,21,6333,301.571429
25,SUP026,Roberts-Williams,P005,6,Weekly,1,20,4965,248.250000
26,SUP027,Woods PLC,P002,5,Monthly,3,18,4674,259.666667
27,SUP028,Taylor Ltd,P002,3,Biweekly,2,23,6299,273.869565
28,SUP029,"Duncan, Davidson and Martin",P005,9,Monthly,3,23,6140,266.956522
29,SUP030,"Baker, Dean and Jensen",P002,5,Biweekly,2,16,3319,207.437500
30,SUP031,"Harmon, Davis and Harper",P002,5,Monthly,3,20,5328,266.400000
31,SUP032,Ferguson Group,P005,3,Weekly,1,21,4668,222.285714
32,SUP033,Murphy-Wise,P001,9,Weekly,1,18,4586,254.777778
33,SUP034,"James, Mullen and Cooper",P001,9,Weekly,1,25,7301,292.040000
34,SUP035,Smith PLC,P001,9,Monthly,3,21,6165,293.571429
35,SUP036,"Powers, Olson and Sanchez",P004,9,Weekly,1,10,3078,307.800000
36,SUP037,Kerr-Palmer,P003,8,Weekly,1,16,4101,256.312500
37,SUP038,"Johnson, Turner and Carpenter",P001,8,Biweekly,2,15,3810,254.000000
38,SUP039,Ortega-Manning,P005,3,Monthly,3,22,6557,298.045455
39,SUP040,Wilson-Stanley,P005,4,Weekly,1,24,6311,262.958333
40,SUP041,Brown Ltd,P003,3,Weekly,1,14,4114,293.857143
41,SUP042,"Cross, Scott and Avery",P004,6,Weekly,1,13,3280,252.307692
42,SUP043,Fox Group,P002,9,Biweekly,2,18,5966,331.444444
43,SUP044,Peters-Salas,P004,4,Monthly,3,20,4587,229.350000
44,SUP045,Castro-Townsend,P001,7,Weekly,1,21,6628,315.619048
45,SUP046,"Harris, Patterson and Harris",P002,9,Biweekly,2,19,5668,298.315789
46,SUP047,Nunez-May,P001,4,Biweekly,2,19,4855,255.526316
47,SUP048,Williams Inc,P003,4,Biweekly,2,25,6899,275.960000
48,SUP049,Obrien-Jones,P005,9,Biweekly,2,19,5371,282.684211
49,SUP050,"Sosa, Cain and Cummings",P003,8,Weekly,1,30,8576,285.866667

MISSING VALUES
----------------------------------------------------------------------

Supplier_ID               0
Supplier_Name             0
Product_ID                0
Lead_Time (days)          0
Order_Frequency           0
Order_Frequency_Code      0
Purchase_Orders           0
Total_Quantity_Ordered    0
Average_Order_Quantity    0
dtype: int64

======================================================================
CLUSTERING FEATURE SUMMARY
======================================================================

,Lead_Time (days),Order_Frequency_Code,Purchase_Orders,Total_Quantity_Ordered,Average_Order_Quantity
count,50.000000,50.000000,50.000000,50.000000,50.000000
mean,6.220000,1.900000,20.000000,5529.760000,275.955331
std,2.131302,0.814411,4.257047,1351.752386,27.382758
min,3.000000,1.000000,10.000000,3078.000000,207.437500
25%,4.000000,1.000000,18.000000,4563.500000,255.056579
50%,6.000000,2.000000,19.500000,5349.500000,276.520000
75%,8.000000,3.000000,21.750000,6308.000000,295.740253
max,9.000000,3.000000,33.000000,9350.000000,331.444444

======================================================================
SUPPLIER MASTER LEAD-TIME DISTRIBUTION
======================================================================

   Lead_Time (days)  count
0                 3      4
1                 4     12
2                 5      5
3                 6      7
4                 7      4
5                 8      6
6                 9     12

======================================================================
ORDER FREQUENCY ENCODING
======================================================================

  Order_Frequency  Order_Frequency_Code
0          Weekly                     1
4        Biweekly                     2
2         Monthly                     3

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 10: K-MEANS SUPPLIER CLUSTERING
# ============================================================

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("=" * 70)
print("K-MEANS SUPPLIER CLUSTERING")
print("=" * 70)


# ------------------------------------------------------------
# 1. Select Clustering Features
# ------------------------------------------------------------

cluster_features = [
    'Lead_Time (days)',
    'Order_Frequency_Code',
    'Purchase_Orders',
    'Total_Quantity_Ordered',
    'Average_Order_Quantity'
]

X = supplier_cluster[cluster_features].copy()


# ------------------------------------------------------------
# 2. Standardize Features
# ------------------------------------------------------------

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


# ------------------------------------------------------------
# 3. Test Multiple Values of K
# ------------------------------------------------------------

silhouette_results = []

for k in range(2, 6):

    kmeans_test = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans_test.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    silhouette_results.append({
        'Number_of_Clusters': k,
        'Silhouette_Score': score
    })


silhouette_df = pd.DataFrame(
    silhouette_results
)


# ------------------------------------------------------------
# 4. Display Silhouette Scores
# ------------------------------------------------------------

print("\nSILHOUETTE SCORE BY NUMBER OF CLUSTERS")
print("-" * 70)

display(silhouette_df)


# ------------------------------------------------------------
# 5. Select Best K
# ------------------------------------------------------------

best_k = int(
    silhouette_df.loc[
        silhouette_df['Silhouette_Score'].idxmax(),
        'Number_of_Clusters'
    ]
)

best_score = silhouette_df['Silhouette_Score'].max()

print(f"\nSelected Number of Clusters : {best_k}")
print(f"Silhouette Score             : {best_score:.4f}")


# ------------------------------------------------------------
# 6. Final K-Means Model
# ------------------------------------------------------------

kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

supplier_cluster['Cluster'] = (
    kmeans.fit_predict(X_scaled) + 1
)


# ------------------------------------------------------------
# 7. Cluster Distribution
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CLUSTER DISTRIBUTION")
print("=" * 70)

cluster_distribution = (
    supplier_cluster['Cluster']
    .value_counts()
    .sort_index()
    .reset_index()
)

cluster_distribution.columns = [
    'Cluster',
    'Supplier_Count'
]

display(cluster_distribution)


# ------------------------------------------------------------
# 8. Supplier Cluster Results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SUPPLIER CLUSTER ASSIGNMENTS")
print("=" * 70)

display(
    supplier_cluster[
        [
            'Supplier_ID',
            'Supplier_Name',
            'Product_ID',
            'Lead_Time (days)',
            'Order_Frequency',
            'Purchase_Orders',
            'Total_Quantity_Ordered',
            'Average_Order_Quantity',
            'Cluster'
        ]
    ]
    .sort_values(
        ['Cluster', 'Lead_Time (days)']
    )
)


# ------------------------------------------------------------
# 9. Cluster Profile
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CLUSTER PROFILE")
print("=" * 70)

cluster_profile = (
    supplier_cluster
    .groupby('Cluster')
    .agg(
        Supplier_Count=('Supplier_ID', 'count'),
        Average_Lead_Time=('Lead_Time (days)', 'mean'),
        Average_Order_Frequency_Code=(
            'Order_Frequency_Code',
            'mean'
        ),
        Average_Purchase_Orders=(
            'Purchase_Orders',
            'mean'
        ),
        Average_Total_Quantity_Ordered=(
            'Total_Quantity_Ordered',
            'mean'
        ),
        Average_Order_Quantity=(
            'Average_Order_Quantity',
            'mean'
        )
    )
    .reset_index()
)

display(cluster_profile)

======================================================================
K-MEANS SUPPLIER CLUSTERING
======================================================================

SILHOUETTE SCORE BY NUMBER OF CLUSTERS
----------------------------------------------------------------------

   Number_of_Clusters  Silhouette_Score
0                   2          0.273168
1                   3          0.275924
2                   4          0.241685
3                   5          0.240681

Selected Number of Clusters : 3
Silhouette Score             : 0.2759

======================================================================
CLUSTER DISTRIBUTION
======================================================================

   Cluster  Supplier_Count
0        1              23
1        2              16
2        3              11

======================================================================
SUPPLIER CLUSTER ASSIGNMENTS
======================================================================

,Supplier_ID,Supplier_Name,Product_ID,Lead_Time (days),Order_Frequency,Purchase_Orders,Total_Quantity_Ordered,Average_Order_Quantity,Cluster
31,SUP032,Ferguson Group,P005,3,Weekly,21,4668,222.285714,1
40,SUP041,Brown Ltd,P003,3,Weekly,14,4114,293.857143,1
2,SUP003,Acosta Inc,P005,4,Monthly,22,5521,250.954545,1
8,SUP009,Baker LLC,P001,4,Weekly,15,3780,252.000000,1
14,SUP015,Watson Ltd,P002,4,Biweekly,16,4556,284.750000,1
18,SUP019,Bowers and Sons,P003,4,Weekly,20,5098,254.900000,1
20,SUP021,Robertson LLC,P001,4,Biweekly,19,5274,277.578947,1
21,SUP022,"Alvarado, Ramirez and Taylor",P001,4,Biweekly,17,4523,266.058824,1
23,SUP024,Thompson-Hebert,P001,4,Biweekly,19,5075,267.105263,1
43,SUP044,Peters-Salas,P004,4,Monthly,20,4587,229.350000,1
46,SUP047,Nunez-May,P001,4,Biweekly,19,4855,255.526316,1
17,SUP018,Wilson Inc,P005,5,Weekly,19,4496,236.631579,1
26,SUP027,Woods PLC,P002,5,Monthly,18,4674,259.666667,1
29,SUP030,"Baker, Dean and Jensen",P002,5,Biweekly,16,3319,207.437500,1
30,SUP031,"Harmon, Davis and Harper",P002,5,Monthly,20,5328,266.400000,1
19,SUP020,"Porter, Daniels and Stewart",P003,6,Monthly,18,4279,237.722222,1
25,SUP026,Roberts-Williams,P005,6,Weekly,20,4965,248.250000,1
41,SUP042,"Cross, Scott and Avery",P004,6,Weekly,13,3280,252.307692,1
12,SUP013,"Norman, Welch and Foster",P004,7,Biweekly,16,4369,273.062500,1
16,SUP017,Ayers Ltd,P005,7,Monthly,19,4690,246.842105,1
36,SUP037,Kerr-Palmer,P003,8,Weekly,16,4101,256.312500,1
37,SUP038,"Johnson, Turner and Carpenter",P001,8,Biweekly,15,3810,254.000000,1
32,SUP033,Murphy-Wise,P001,9,Weekly,18,4586,254.777778,1
24,SUP025,Rose Inc,P005,5,Monthly,21,6333,301.571429,2
5,SUP006,"Hood, Barrera and Woodard",P001,6,Monthly,14,4498,321.285714,2
11,SUP012,"Wright, White and Gonzalez",P004,6,Monthly,20,6159,307.950000,2
22,SUP023,Smith and Sons,P002,6,Monthly,19,6019,316.789474,2
44,SUP045,Castro-Townsend,P001,7,Weekly,21,6628,315.619048,2
15,SUP016,Johnson Group,P002,8,Biweekly,21,6039,287.571429,2
0,SUP001,Murray-Ramirez,P002,9,Weekly,18,5328,296.000000,2
1,SUP002,"Thomas, Meyer and Campbell",P005,9,Weekly,21,6016,286.476190,2
6,SUP007,"Meyers, Miller and Young",P002,9,Weekly,19,5620,295.789474,2
9,SUP010,Wright PLC,P003,9,Monthly,20,6451,322.550000,2
28,SUP029,"Duncan, Davidson and Martin",P005,9,Monthly,23,6140,266.956522,2
34,SUP035,Smith PLC,P001,9,Monthly,21,6165,293.571429,2
35,SUP036,"Powers, Olson and Sanchez",P004,9,Weekly,10,3078,307.800000,2
42,SUP043,Fox Group,P002,9,Biweekly,18,5966,331.444444,2
45,SUP046,"Harris, Patterson and Harris",P002,9,Biweekly,19,5668,298.315789,2
48,SUP049,Obrien-Jones,P005,9,Biweekly,19,5371,282.684211,2
27,SUP028,Taylor Ltd,P002,3,Biweekly,23,6299,273.869565,3
38,SUP039,Ortega-Manning,P005,3,Monthly,22,6557,298.045455,3
10,SUP011,"Peterson, Thomas and Page",P004,4,Biweekly,27,7267,269.148148,3
39,SUP040,Wilson-Stanley,P005,4,Weekly,24,6311,262.958333,3
47,SUP048,Williams Inc,P003,4,Biweekly,25,6899,275.960000,3
4,SUP005,"Johnson, Wise and Barr",P003,6,Biweekly,27,7981,295.592593,3
13,SUP014,Brown LLC,P001,7,Biweekly,25,7593,303.720000,3
3,SUP004,"Evans, Brown and Turner",P002,8,Weekly,25,6927,277.080000,3
7,SUP008,Edwards-Barnes,P005,8,Weekly,33,9350,283.333333,3
49,SUP050,"Sosa, Cain and Cummings",P003,8,Weekly,30,8576,285.866667,3
33,SUP034,"James, Mullen and Cooper",P001,9,Weekly,25,7301,292.040000,3

======================================================================
CLUSTER PROFILE
======================================================================

,Cluster,Supplier_Count,Average_Lead_Time,Average_Order_Frequency_Code,Average_Purchase_Orders,Average_Total_Quantity_Ordered,Average_Order_Quantity
0,1,23,5.173913,1.869565,17.826087,4519.478261,254.251187
1,2,16,8.000000,2.125000,19.000000,5717.437500,302.023447
2,3,11,5.818182,1.636364,26.000000,7369.181818,283.419463

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 11: DEMAND FORECASTING DATA PREPARATION
# ============================================================

print("=" * 70)
print("DEMAND FORECASTING DATA PREPARATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Create Monthly Demand Dataset
# ------------------------------------------------------------

monthly_demand = (
    sales.groupby(
        sales['Sale_Date'].dt.to_period('M')
    )
    .agg(
        Total_Quantity_Sold=('Quantity_Sold', 'sum'),
        Total_Revenue=('Revenue', 'sum'),
        Transaction_Count=('Sale_ID', 'count')
    )
    .reset_index()
)

monthly_demand['Month'] = (
    monthly_demand['Sale_Date']
    .dt.to_timestamp()
)

monthly_demand = monthly_demand.drop(
    columns=['Sale_Date']
)


# ------------------------------------------------------------
# 2. Sort Chronologically
# ------------------------------------------------------------

monthly_demand = monthly_demand.sort_values(
    'Month'
).reset_index(drop=True)


# ------------------------------------------------------------
# 3. Check Date Range
# ------------------------------------------------------------

print("\nMONTHLY DEMAND DATE RANGE")
print("-" * 70)

print(
    f"First Month : "
    f"{monthly_demand['Month'].min().strftime('%Y-%m')}"
)

print(
    f"Last Month  : "
    f"{monthly_demand['Month'].max().strftime('%Y-%m')}"
)

print(
    f"Number of Monthly Records : "
    f"{len(monthly_demand)}"
)


# ------------------------------------------------------------
# 4. Check for Missing Months
# ------------------------------------------------------------

expected_months = pd.date_range(
    start=monthly_demand['Month'].min(),
    end=monthly_demand['Month'].max(),
    freq='MS'
)

actual_months = set(monthly_demand['Month'])

missing_months = [
    month for month in expected_months
    if month not in actual_months
]

print("\nMONTH CONTINUITY CHECK")
print("-" * 70)

print(
    f"Expected Months : {len(expected_months)}"
)

print(
    f"Actual Months   : {len(actual_months)}"
)

print(
    f"Missing Months  : {len(missing_months)}"
)

if len(missing_months) > 0:
    print("\nMissing Month List:")
    print(missing_months)


# ------------------------------------------------------------
# 5. Monthly Demand Statistics
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MONTHLY DEMAND STATISTICS")
print("=" * 70)

display(
    monthly_demand[
        [
            'Month',
            'Total_Quantity_Sold',
            'Total_Revenue',
            'Transaction_Count'
        ]
    ].describe()
)


# ------------------------------------------------------------
# 6. First 10 Months
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FIRST 10 MONTHS")
print("=" * 70)

display(
    monthly_demand.head(10)
)


# ------------------------------------------------------------
# 7. Last 10 Months
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LAST 10 MONTHS")
print("=" * 70)

display(
    monthly_demand.tail(10)
)


# ------------------------------------------------------------
# 8. Monthly Demand Change
# ------------------------------------------------------------

monthly_demand['Demand_Change'] = (
    monthly_demand['Total_Quantity_Sold']
    .diff()
)

monthly_demand['Demand_Growth_%'] = (
    monthly_demand['Total_Quantity_Sold']
    .pct_change() * 100
)


# ------------------------------------------------------------
# 9. Demand Variability
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DEMAND VARIABILITY")
print("=" * 70)

print(
    f"Average Monthly Demand : "
    f"{monthly_demand['Total_Quantity_Sold'].mean():,.2f}"
)

print(
    f"Minimum Monthly Demand : "
    f"{monthly_demand['Total_Quantity_Sold'].min():,.2f}"
)

print(
    f"Maximum Monthly Demand : "
    f"{monthly_demand['Total_Quantity_Sold'].max():,.2f}"
)

print(
    f"Demand Std. Deviation  : "
    f"{monthly_demand['Total_Quantity_Sold'].std():,.2f}"
)


# ------------------------------------------------------------
# 10. Product-Level Monthly Demand
# ------------------------------------------------------------

product_monthly_demand = (
    sales.groupby(
        [
            sales['Sale_Date'].dt.to_period('M'),
            'Product_ID'
        ]
    )
    .agg(
        Quantity_Sold=('Quantity_Sold', 'sum'),
        Revenue=('Revenue', 'sum')
    )
    .reset_index()
)

product_monthly_demand['Month'] = (
    product_monthly_demand['Sale_Date']
    .dt.to_timestamp()
)

product_monthly_demand = (
    product_monthly_demand
    .drop(columns=['Sale_Date'])
    .sort_values(['Product_ID', 'Month'])
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("PRODUCT-LEVEL MONTHLY DEMAND")
print("=" * 70)

display(
    product_monthly_demand.head(15)
)

======================================================================
DEMAND FORECASTING DATA PREPARATION
======================================================================

MONTHLY DEMAND DATE RANGE
----------------------------------------------------------------------
First Month : 2024-01
Last Month  : 2037-09
Number of Monthly Records : 165

MONTH CONTINUITY CHECK
----------------------------------------------------------------------
Expected Months : 165
Actual Months   : 165
Missing Months  : 0

======================================================================
MONTHLY DEMAND STATISTICS
======================================================================

,Month,Total_Quantity_Sold,Total_Revenue,Transaction_Count
count,165,165.000000,1.650000e+02,165.000000
mean,2030-10-31 13:49:05.454545408,7831.042424,7.628486e+05,30.303030
min,2024-01-01 00:00:00,1782.000000,2.878780e+05,8.000000
25%,2027-06-01 00:00:00,7327.000000,7.209440e+05,30.000000
50%,2030-11-01 00:00:00,7896.000000,7.690050e+05,31.000000
75%,2034-04-01 00:00:00,8468.000000,8.044440e+05,31.000000
max,2037-09-01 00:00:00,9509.000000,1.037436e+06,31.000000
std,NaN,917.812393,8.315418e+04,1.926782

======================================================================
FIRST 10 MONTHS
======================================================================

   Total_Quantity_Sold  Total_Revenue  Transaction_Count      Month
0                 8623         706316                 31 2024-01-01
1                 7334         748910                 29 2024-02-01
2                 7327         749353                 31 2024-03-01
3                 8389         770649                 30 2024-04-01
4                 8277         793790                 31 2024-05-01
5                 9040         775810                 30 2024-06-01
6                 7652         801268                 31 2024-07-01
7                 8210         780492                 31 2024-08-01
8                 7401         823266                 30 2024-09-01
9                 8151         594306                 31 2024-10-01

======================================================================
LAST 10 MONTHS
======================================================================

     Total_Quantity_Sold  Total_Revenue  Transaction_Count      Month
155                 9108         799441                 31 2036-12-01
156                 7927         812684                 31 2037-01-01
157                 8434         635952                 28 2037-02-01
158                 7043         701480                 31 2037-03-01
159                 7179         720944                 30 2037-04-01
160                 8826         734901                 31 2037-05-01
161                 7585         664893                 30 2037-06-01
162                 6738         696360                 31 2037-07-01
163                 8385         850017                 31 2037-08-01
164                 1782         287878                  8 2037-09-01

======================================================================
DEMAND VARIABILITY
======================================================================
Average Monthly Demand : 7,831.04
Minimum Monthly Demand : 1,782.00
Maximum Monthly Demand : 9,509.00
Demand Std. Deviation  : 917.81

======================================================================
PRODUCT-LEVEL MONTHLY DEMAND
======================================================================

   Product_ID  Quantity_Sold  Revenue      Month
0        P001            902    97996 2024-01-01
1        P001           1322   158814 2024-02-01
2        P001           3243   348879 2024-03-01
3        P001           2239   187431 2024-04-01
4        P001           1266   120507 2024-05-01
5        P001            269    28852 2024-06-01
6        P001           1051   153521 2024-07-01
7        P001           1349   129621 2024-08-01
8        P001           1385   177734 2024-09-01
9        P001           1687   109228 2024-10-01
10       P001            973    54775 2024-11-01
11       P001           1433    99323 2024-12-01
12       P001           1609   150403 2025-01-01
13       P001           1326    88099 2025-02-01
14       P001           1471   209854 2025-03-01

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 12: PRODUCT-LEVEL FORECASTING DATASET PREPARATION
# ============================================================

print("=" * 70)
print("PRODUCT-LEVEL FORECASTING DATASET PREPARATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Create Complete Product-Month Calendar
# ------------------------------------------------------------

products = sorted(sales['Product_ID'].unique())

all_months = pd.date_range(
    start=sales['Sale_Date'].min().to_period('M').to_timestamp(),
    end=sales['Sale_Date'].max().to_period('M').to_timestamp(),
    freq='MS'
)

product_month_calendar = pd.MultiIndex.from_product(
    [products, all_months],
    names=['Product_ID', 'Month']
).to_frame(index=False)


# ------------------------------------------------------------
# 2. Aggregate Actual Product-Level Demand
# ------------------------------------------------------------

product_month_actual = (
    sales.groupby(
        [
            sales['Sale_Date'].dt.to_period('M').dt.to_timestamp(),
            'Product_ID'
        ]
    )
    .agg(
        Quantity_Sold=('Quantity_Sold', 'sum'),
        Revenue=('Revenue', 'sum'),
        Transaction_Count=('Sale_ID', 'count')
    )
    .reset_index()
    .rename(columns={'Sale_Date': 'Month'})
)


# ------------------------------------------------------------
# 3. Merge with Complete Calendar
# ------------------------------------------------------------

product_forecast_data = product_month_calendar.merge(
    product_month_actual,
    on=['Product_ID', 'Month'],
    how='left'
)


# ------------------------------------------------------------
# 4. Identify Missing Product-Month Observations
# ------------------------------------------------------------

missing_product_months = product_forecast_data[
    product_forecast_data['Quantity_Sold'].isna()
].copy()

print("\nPRODUCT-MONTH COMPLETENESS")
print("-" * 70)

print(
    f"Products : {len(products)}"
)

print(
    f"Months   : {len(all_months)}"
)

print(
    f"Expected Product-Month Records : "
    f"{len(products) * len(all_months)}"
)

print(
    f"Actual Product-Month Records   : "
    f"{len(product_forecast_data)}"
)

print(
    f"Missing Product-Month Records : "
    f"{len(missing_product_months)}"
)


# ------------------------------------------------------------
# 5. Display Missing Product-Month Records
# ------------------------------------------------------------

if len(missing_product_months) > 0:

    print("\nMissing Product-Month Records:")

    display(
        missing_product_months.head(20)
    )

else:

    print(
        "\nAll products have observations for every month."
    )


# ------------------------------------------------------------
# 6. Product-Level Forecasting Summary
# ------------------------------------------------------------

product_forecast_summary = (
    product_forecast_data
    .groupby('Product_ID')
    .agg(
        Months=('Month', 'count'),
        Total_Quantity=('Quantity_Sold', 'sum'),
        Average_Monthly_Demand=('Quantity_Sold', 'mean'),
        Minimum_Monthly_Demand=('Quantity_Sold', 'min'),
        Maximum_Monthly_Demand=('Quantity_Sold', 'max'),
        Demand_Std_Dev=('Quantity_Sold', 'std'),
        Total_Revenue=('Revenue', 'sum')
    )
    .reset_index()
)


print("\n" + "=" * 70)
print("PRODUCT-LEVEL DEMAND SUMMARY")
print("=" * 70)

display(
    product_forecast_summary
)


# ------------------------------------------------------------
# 7. Latest Product-Level Observations
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LATEST PRODUCT-LEVEL OBSERVATIONS")
print("=" * 70)

latest_month = product_forecast_data['Month'].max()

display(
    product_forecast_data[
        product_forecast_data['Month'] == latest_month
    ].sort_values('Product_ID')
)


# ------------------------------------------------------------
# 8. Check Zero-Demand Months
# ------------------------------------------------------------

zero_demand_records = product_forecast_data[
    product_forecast_data['Quantity_Sold'].fillna(0) == 0
]

print("\n" + "=" * 70)
print("ZERO-DEMAND MONTH CHECK")
print("=" * 70)

print(
    f"Product-Month records with zero demand : "
    f"{len(zero_demand_records)}"
)

if len(zero_demand_records) > 0:
    display(
        zero_demand_records.head(20)
    )

======================================================================
PRODUCT-LEVEL FORECASTING DATASET PREPARATION
======================================================================

PRODUCT-MONTH COMPLETENESS
----------------------------------------------------------------------
Products : 5
Months   : 165
Expected Product-Month Records : 825
Actual Product-Month Records   : 825
Missing Product-Month Records : 2

Missing Product-Month Records:

    Product_ID      Month  Quantity_Sold  Revenue  Transaction_Count
34        P001 2026-11-01            NaN      NaN                NaN
329       P002 2037-09-01            NaN      NaN                NaN

======================================================================
PRODUCT-LEVEL DEMAND SUMMARY
======================================================================

,Product_ID,Months,Total_Quantity,Average_Monthly_Demand,Minimum_Monthly_Demand,Maximum_Monthly_Demand,Demand_Std_Dev,Total_Revenue
0,P001,165,260296.0,1587.170732,90.0,3712.0,723.491327,25355109.0
1,P002,165,269100.0,1640.853659,185.0,3372.0,695.602385,26084882.0
2,P003,165,249297.0,1510.890909,40.0,3448.0,633.942898,24697925.0
3,P004,165,258635.0,1567.484848,250.0,3605.0,684.609570,24835649.0
4,P005,165,254794.0,1544.206061,271.0,3769.0,678.729215,24896449.0

======================================================================
LATEST PRODUCT-LEVEL OBSERVATIONS
======================================================================

    Product_ID      Month  Quantity_Sold  Revenue  Transaction_Count
164       P001 2037-09-01          372.0  78789.0                2.0
329       P002 2037-09-01            NaN      NaN                NaN
494       P003 2037-09-01          394.0  82343.0                2.0
659       P004 2037-09-01          745.0  85018.0                3.0
824       P005 2037-09-01          271.0  41728.0                1.0

======================================================================
ZERO-DEMAND MONTH CHECK
======================================================================
Product-Month records with zero demand : 2

    Product_ID      Month  Quantity_Sold  Revenue  Transaction_Count
34        P001 2026-11-01            NaN      NaN                NaN
329       P002 2037-09-01            NaN      NaN                NaN

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 13: DIAGNOSE MISSING PRODUCT-MONTH OBSERVATIONS
# ============================================================

print("=" * 70)
print("MISSING PRODUCT-MONTH DIAGNOSTIC")
print("=" * 70)

missing_pairs = (
    product_forecast_data[
        product_forecast_data['Quantity_Sold'].isna()
    ][['Product_ID', 'Month']]
    .copy()
)

print("\nMISSING PRODUCT-MONTH RECORDS")
print("-" * 70)
display(missing_pairs)


# ------------------------------------------------------------
# 1. Show Surrounding Months for Each Missing Record
# ------------------------------------------------------------

for _, row in missing_pairs.iterrows():

    product = row['Product_ID']
    missing_month = row['Month']

    print("\n" + "=" * 70)
    print(f"PRODUCT: {product} | MISSING MONTH: {missing_month.strftime('%Y-%m')}")
    print("=" * 70)

    start_month = missing_month - pd.DateOffset(months=3)
    end_month = missing_month + pd.DateOffset(months=3)

    surrounding_data = product_forecast_data[
        (product_forecast_data['Product_ID'] == product) &
        (product_forecast_data['Month'] >= start_month) &
        (product_forecast_data['Month'] <= end_month)
    ].copy()

    display(
        surrounding_data[
            [
                'Product_ID',
                'Month',
                'Quantity_Sold',
                'Revenue',
                'Transaction_Count'
            ]
        ]
    )


# ------------------------------------------------------------
# 2. Check Whether the Missing Month Has Any Sales Row
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DIRECT SALES-DATA CHECK")
print("=" * 70)

for _, row in missing_pairs.iterrows():

    product = row['Product_ID']
    missing_month = row['Month']

    sales_check = sales[
        (sales['Product_ID'] == product) &
        (sales['Sale_Date'].dt.to_period('M') == missing_month.to_period('M'))
    ]

    print(
        f"{product} | {missing_month.strftime('%Y-%m')} "
        f"| Sales Rows Found: {len(sales_check)}"
    )


# ------------------------------------------------------------
# 3. Check Whether These Are the Only Missing Months
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING-MONTH COUNT BY PRODUCT")
print("=" * 70)

missing_by_product = (
    product_forecast_data[
        product_forecast_data['Quantity_Sold'].isna()
    ]
    .groupby('Product_ID')
    .size()
    .reset_index(name='Missing_Months')
)

display(missing_by_product)


# ------------------------------------------------------------
# 4. Check Final Month Coverage
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL MONTH COVERAGE")
print("=" * 70)

final_month = sales['Sale_Date'].max().to_period('M')

final_month_data = (
    sales[
        sales['Sale_Date'].dt.to_period('M') == final_month
    ]
    .groupby('Product_ID')
    .agg(
        Sales_Rows=('Sale_ID', 'count'),
        Quantity_Sold=('Quantity_Sold', 'sum'),
        Revenue=('Revenue', 'sum')
    )
    .reset_index()
)

display(final_month_data)


# ------------------------------------------------------------
# 5. Count Number of Calendar Days Represented
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL MONTH DAY COVERAGE")
print("=" * 70)

final_month_sales = sales[
    sales['Sale_Date'].dt.to_period('M') == final_month
].copy()

days_with_sales = final_month_sales['Sale_Date'].dt.day.nunique()

calendar_days = final_month.days_in_month

print(f"Final Month : {final_month}")
print(f"Calendar Days in Month : {calendar_days}")
print(f"Days Represented in Sales Data : {days_with_sales}")
print(f"Last Sale Date : {sales['Sale_Date'].max().strftime('%Y-%m-%d')}")

======================================================================
MISSING PRODUCT-MONTH DIAGNOSTIC
======================================================================

MISSING PRODUCT-MONTH RECORDS
----------------------------------------------------------------------

    Product_ID      Month
34        P001 2026-11-01
329       P002 2037-09-01

======================================================================
PRODUCT: P001 | MISSING MONTH: 2026-11
======================================================================

   Product_ID      Month  Quantity_Sold   Revenue  Transaction_Count
31       P001 2026-08-01         1286.0  152898.0                5.0
32       P001 2026-09-01         1330.0  216457.0                9.0
33       P001 2026-10-01         2297.0  259289.0               10.0
34       P001 2026-11-01            NaN       NaN                NaN
35       P001 2026-12-01         2196.0  213409.0                9.0
36       P001 2027-01-01         1313.0  171718.0                6.0
37       P001 2027-02-01         3399.0  234592.0               11.0

======================================================================
PRODUCT: P002 | MISSING MONTH: 2037-09
======================================================================

    Product_ID      Month  Quantity_Sold   Revenue  Transaction_Count
326       P002 2037-06-01         1121.0   34612.0                3.0
327       P002 2037-07-01         1626.0  179849.0                8.0
328       P002 2037-08-01         1707.0  222328.0                7.0
329       P002 2037-09-01            NaN       NaN                NaN

======================================================================
DIRECT SALES-DATA CHECK
======================================================================
P001 | 2026-11 | Sales Rows Found: 0
P002 | 2037-09 | Sales Rows Found: 0

======================================================================
MISSING-MONTH COUNT BY PRODUCT
======================================================================

  Product_ID  Missing_Months
0       P001               1
1       P002               1

======================================================================
FINAL MONTH COVERAGE
======================================================================

  Product_ID  Sales_Rows  Quantity_Sold  Revenue
0       P001           2            372    78789
1       P003           2            394    82343
2       P004           3            745    85018
3       P005           1            271    41728

======================================================================
FINAL MONTH DAY COVERAGE
======================================================================
Final Month : 2037-09
Calendar Days in Month : 30
Days Represented in Sales Data : 8
Last Sale Date : 2037-09-08

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 14: BUILD FINAL FORECASTING DATASET
# ============================================================

print("=" * 70)
print("FINAL FORECASTING DATASET")
print("=" * 70)


# ------------------------------------------------------------
# 1. Copy Product-Month Dataset
# ------------------------------------------------------------

forecast_data = product_forecast_data.copy()


# ------------------------------------------------------------
# 2. Identify the Incomplete Final Month
# ------------------------------------------------------------

final_complete_month = (
    sales['Sale_Date'].max()
    .to_period('M')
    - 1
).to_timestamp()

print("\nFORECASTING CUTOFF")
print("-" * 70)
print(
    f"Last Sale Date : "
    f"{sales['Sale_Date'].max().strftime('%Y-%m-%d')}"
)
print(
    f"Incomplete Final Month : "
    f"{sales['Sale_Date'].max().strftime('%Y-%m')}"
)
print(
    f"Last Complete Month : "
    f"{final_complete_month.strftime('%Y-%m')}"
)


# ------------------------------------------------------------
# 3. Remove Incomplete Final Month
# ------------------------------------------------------------

forecast_data = forecast_data[
    forecast_data['Month'] <= final_complete_month
].copy()


# ------------------------------------------------------------
# 4. Fill the Genuine Zero-Demand Month
# ------------------------------------------------------------

zero_demand_month = (
    (forecast_data['Product_ID'] == 'P001') &
    (forecast_data['Month'] == pd.Timestamp('2026-11-01'))
)

print("\nZERO-DEMAND MONTH HANDLING")
print("-" * 70)

print(
    "P001 | 2026-11 | "
    f"Records before filling: "
    f"{forecast_data.loc[zero_demand_month, 'Quantity_Sold'].isna().sum()}"
)

forecast_data.loc[zero_demand_month, 'Quantity_Sold'] = 0
forecast_data.loc[zero_demand_month, 'Revenue'] = 0
forecast_data.loc[zero_demand_month, 'Transaction_Count'] = 0


# ------------------------------------------------------------
# 5. Check Remaining Missing Values
# ------------------------------------------------------------

print("\nMISSING VALUE CHECK")
print("-" * 70)

print(
    forecast_data[
        ['Quantity_Sold', 'Revenue', 'Transaction_Count']
    ].isna().sum()
)


# ------------------------------------------------------------
# 6. Dataset Size
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL DATASET SIZE")
print("=" * 70)

print(
    f"Products : "
    f"{forecast_data['Product_ID'].nunique()}"
)

print(
    f"Months : "
    f"{forecast_data['Month'].nunique()}"
)

print(
    f"Expected Product-Month Records : "
    f"{forecast_data['Product_ID'].nunique() * forecast_data['Month'].nunique()}"
)

print(
    f"Actual Product-Month Records : "
    f"{len(forecast_data)}"
)


# ------------------------------------------------------------
# 7. Final Forecasting Date Range
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL FORECASTING DATE RANGE")
print("=" * 70)

print(
    f"First Month : "
    f"{forecast_data['Month'].min().strftime('%Y-%m')}"
)

print(
    f"Last Month : "
    f"{forecast_data['Month'].max().strftime('%Y-%m')}"
)


# ------------------------------------------------------------
# 8. Product-Level Final Summary
# ------------------------------------------------------------

final_product_summary = (
    forecast_data
    .groupby('Product_ID')
    .agg(
        Months=('Month', 'count'),
        Total_Demand=('Quantity_Sold', 'sum'),
        Average_Monthly_Demand=('Quantity_Sold', 'mean'),
        Minimum_Demand=('Quantity_Sold', 'min'),
        Maximum_Demand=('Quantity_Sold', 'max'),
        Demand_Std_Dev=('Quantity_Sold', 'std')
    )
    .reset_index()
)

print("\n" + "=" * 70)
print("FINAL PRODUCT-LEVEL FORECASTING SUMMARY")
print("=" * 70)

display(final_product_summary)


# ------------------------------------------------------------
# 9. Verify P001 Zero-Demand Month
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("P001 ZERO-DEMAND VERIFICATION")
print("=" * 70)

display(
    forecast_data[
        (forecast_data['Product_ID'] == 'P001') &
        (
            forecast_data['Month'].between(
                pd.Timestamp('2026-10-01'),
                pd.Timestamp('2026-12-01')
            )
        )
    ]
)


# ------------------------------------------------------------
# 10. Verify Final Month Was Removed
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL MONTH EXCLUSION CHECK")
print("=" * 70)

print(
    "2037-09 present in forecasting dataset:",
    (forecast_data['Month'] == pd.Timestamp('2037-09-01')).any()
)

======================================================================
FINAL FORECASTING DATASET
======================================================================

FORECASTING CUTOFF
----------------------------------------------------------------------
Last Sale Date : 2037-09-08
Incomplete Final Month : 2037-09
Last Complete Month : 2037-08

ZERO-DEMAND MONTH HANDLING
----------------------------------------------------------------------
P001 | 2026-11 | Records before filling: 1

MISSING VALUE CHECK
----------------------------------------------------------------------
Quantity_Sold        0
Revenue              0
Transaction_Count    0
dtype: int64

======================================================================
FINAL DATASET SIZE
======================================================================
Products : 5
Months : 164
Expected Product-Month Records : 820
Actual Product-Month Records : 820

======================================================================
FINAL FORECASTING DATE RANGE
======================================================================
First Month : 2024-01
Last Month : 2037-08

======================================================================
FINAL PRODUCT-LEVEL FORECASTING SUMMARY
======================================================================

,Product_ID,Months,Total_Demand,Average_Monthly_Demand,Minimum_Demand,Maximum_Demand,Demand_Std_Dev
0,P001,164,259924.0,1584.902439,0.0,3712.0,727.894259
1,P002,164,269100.0,1640.853659,185.0,3372.0,695.602385
2,P003,164,248903.0,1517.701220,40.0,3448.0,629.801110
3,P004,164,257890.0,1572.500000,250.0,3605.0,683.659393
4,P005,164,254523.0,1551.969512,330.0,3769.0,673.419490

======================================================================
P001 ZERO-DEMAND VERIFICATION
======================================================================

   Product_ID      Month  Quantity_Sold   Revenue  Transaction_Count
33       P001 2026-10-01         2297.0  259289.0               10.0
34       P001 2026-11-01            0.0       0.0                0.0
35       P001 2026-12-01         2196.0  213409.0                9.0

======================================================================
FINAL MONTH EXCLUSION CHECK
======================================================================
2037-09 present in forecasting dataset: False

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 15: FORECASTING TRAIN-TEST SPLIT
# ============================================================

print("=" * 70)
print("DEMAND FORECASTING TRAIN-TEST SPLIT")
print("=" * 70)


# ------------------------------------------------------------
# 1. Define Test Period
# ------------------------------------------------------------

all_forecast_months = sorted(
    forecast_data['Month'].unique()
)

test_months = all_forecast_months[-12:]
train_months = all_forecast_months[:-12]

print("\nFORECASTING PERIOD")
print("-" * 70)

print(
    f"Total Complete Months : "
    f"{len(all_forecast_months)}"
)

print(
    f"Training Months : "
    f"{len(train_months)}"
)

print(
    f"Testing Months : "
    f"{len(test_months)}"
)

print(
    f"Training Period : "
    f"{pd.Timestamp(train_months[0]).strftime('%Y-%m')} "
    f"to "
    f"{pd.Timestamp(train_months[-1]).strftime('%Y-%m')}"
)

print(
    f"Testing Period : "
    f"{pd.Timestamp(test_months[0]).strftime('%Y-%m')} "
    f"to "
    f"{pd.Timestamp(test_months[-1]).strftime('%Y-%m')}"
)


# ------------------------------------------------------------
# 2. Create Training and Testing Datasets
# ------------------------------------------------------------

train_data = forecast_data[
    forecast_data['Month'].isin(train_months)
].copy()

test_data = forecast_data[
    forecast_data['Month'].isin(test_months)
].copy()


# ------------------------------------------------------------
# 3. Verify Dataset Sizes
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATASET SIZE VALIDATION")
print("=" * 70)

print(
    f"Training Records : {len(train_data)}"
)

print(
    f"Testing Records  : {len(test_data)}"
)

print(
    f"Expected Training Records : "
    f"{len(train_months) * forecast_data['Product_ID'].nunique()}"
)

print(
    f"Expected Testing Records : "
    f"{len(test_months) * forecast_data['Product_ID'].nunique()}"
)


# ------------------------------------------------------------
# 4. Training/Test Coverage by Product
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TRAINING COVERAGE BY PRODUCT")
print("=" * 70)

train_summary = (
    train_data
    .groupby('Product_ID')
    .agg(
        Months=('Month', 'count'),
        Total_Demand=('Quantity_Sold', 'sum'),
        Average_Demand=('Quantity_Sold', 'mean')
    )
    .reset_index()
)

display(train_summary)


print("\n" + "=" * 70)
print("TESTING COVERAGE BY PRODUCT")
print("=" * 70)

test_summary = (
    test_data
    .groupby('Product_ID')
    .agg(
        Months=('Month', 'count'),
        Total_Demand=('Quantity_Sold', 'sum'),
        Average_Demand=('Quantity_Sold', 'mean')
    )
    .reset_index()
)

display(test_summary)


# ------------------------------------------------------------
# 5. Display Test Period Actual Demand
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TEST PERIOD ACTUAL DEMAND")
print("=" * 70)

test_pivot = (
    test_data
    .pivot(
        index='Month',
        columns='Product_ID',
        values='Quantity_Sold'
    )
    .sort_index()
)

display(test_pivot)


# ------------------------------------------------------------
# 6. Check for Missing Values
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TRAINING / TESTING MISSING VALUE CHECK")
print("=" * 70)

print("Training missing values:")
print(
    train_data['Quantity_Sold'].isna().sum()
)

print("\nTesting missing values:")
print(
    test_data['Quantity_Sold'].isna().sum()
)

======================================================================
DEMAND FORECASTING TRAIN-TEST SPLIT
======================================================================

FORECASTING PERIOD
----------------------------------------------------------------------
Total Complete Months : 164
Training Months : 152
Testing Months : 12
Training Period : 2024-01 to 2036-08
Testing Period : 2036-09 to 2037-08

======================================================================
DATASET SIZE VALIDATION
======================================================================
Training Records : 760
Testing Records  : 60
Expected Training Records : 760
Expected Testing Records : 60

======================================================================
TRAINING COVERAGE BY PRODUCT
======================================================================

  Product_ID  Months  Total_Demand  Average_Demand
0       P001     152      241252.0     1587.184211
1       P002     152      250106.0     1645.434211
2       P003     152      231889.0     1525.585526
3       P004     152      237499.0     1562.493421
4       P005     152      234224.0     1540.947368

======================================================================
TESTING COVERAGE BY PRODUCT
======================================================================

  Product_ID  Months  Total_Demand  Average_Demand
0       P001      12       18672.0     1556.000000
1       P002      12       18994.0     1582.833333
2       P003      12       17014.0     1417.833333
3       P004      12       20391.0     1699.250000
4       P005      12       20299.0     1691.583333

======================================================================
TEST PERIOD ACTUAL DEMAND
======================================================================

Product_ID    P001    P002    P003    P004    P005
Month
2036-09-01  2639.0   894.0  1095.0   575.0  1801.0
2036-10-01  1985.0  2849.0   976.0  1445.0  1746.0
2036-11-01  2059.0  2629.0  1100.0   924.0  1428.0
2036-12-01  2569.0  1619.0  2139.0  1341.0  1440.0
2037-01-01  1295.0   769.0  2603.0  2131.0  1129.0
2037-02-01  1070.0  1996.0  1030.0  1655.0  2683.0
2037-03-01   687.0  1153.0  1456.0  1958.0  1789.0
2037-04-01  1246.0  1768.0   913.0  1949.0  1303.0
2037-05-01  1613.0   863.0   910.0  2858.0  2582.0
2037-06-01  1496.0  1121.0  2347.0  1276.0  1345.0
2037-07-01   768.0  1626.0   926.0  1449.0  1969.0
2037-08-01  1245.0  1707.0  1519.0  2830.0  1084.0

======================================================================
TRAINING / TESTING MISSING VALUE CHECK
======================================================================
Training missing values:
0

Testing missing values:
0

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 16: FORECASTING MODEL EVALUATION
# ============================================================

import numpy as np

print("=" * 70)
print("DEMAND FORECASTING MODEL EVALUATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Helper Functions
# ------------------------------------------------------------

def calculate_mae(actual, predicted):
    return np.mean(np.abs(actual - predicted))


def calculate_rmse(actual, predicted):
    return np.sqrt(np.mean((actual - predicted) ** 2))


def calculate_mape(actual, predicted):
    actual = np.asarray(actual)
    predicted = np.asarray(predicted)

    mask = actual != 0

    return np.mean(
        np.abs(
            (actual[mask] - predicted[mask])
            / actual[mask]
        )
    ) * 100


# ------------------------------------------------------------
# 2. Prepare Evaluation Data
# ------------------------------------------------------------

evaluation_results = []

products = sorted(
    forecast_data['Product_ID'].unique()
)

for product in products:

    product_series = (
        forecast_data[
            forecast_data['Product_ID'] == product
        ]
        .sort_values('Month')
        .set_index('Month')['Quantity_Sold']
    )

    train_series = product_series[
        product_series.index <= pd.Timestamp('2036-08-01')
    ]

    test_series = product_series[
        product_series.index >= pd.Timestamp('2036-09-01')
    ]


    # --------------------------------------------------------
    # 3. Generate Forecasts for Test Period
    # --------------------------------------------------------

    actual = test_series.values


    # 3-Month Moving Average
    ma3_forecast = []

    for i in range(len(test_series)):

        historical_values = product_series[
            product_series.index < test_series.index[i]
        ].tail(3)

        ma3_forecast.append(
            historical_values.mean()
        )


    # 6-Month Moving Average
    ma6_forecast = []

    for i in range(len(test_series)):

        historical_values = product_series[
            product_series.index < test_series.index[i]
        ].tail(6)

        ma6_forecast.append(
            historical_values.mean()
        )


    # 12-Month Seasonal Naive
    seasonal_forecast = []

    for test_month in test_series.index:

        previous_year_month = (
            test_month - pd.DateOffset(years=1)
        )

        seasonal_value = product_series[
            product_series.index == previous_year_month
        ]

        if len(seasonal_value) > 0:
            seasonal_forecast.append(
                seasonal_value.iloc[0]
            )
        else:
            seasonal_forecast.append(np.nan)


    # --------------------------------------------------------
    # 4. Evaluate Each Method
    # --------------------------------------------------------

    model_forecasts = {
        '3-Month Moving Average': np.array(ma3_forecast),
        '6-Month Moving Average': np.array(ma6_forecast),
        '12-Month Seasonal Naive': np.array(seasonal_forecast)
    }


    for model_name, predictions in model_forecasts.items():

        valid_mask = ~np.isnan(predictions)

        actual_valid = actual[valid_mask]
        predicted_valid = predictions[valid_mask]

        evaluation_results.append({
            'Product_ID': product,
            'Model': model_name,
            'MAE': calculate_mae(
                actual_valid,
                predicted_valid
            ),
            'RMSE': calculate_rmse(
                actual_valid,
                predicted_valid
            ),
            'MAPE_%': calculate_mape(
                actual_valid,
                predicted_valid
            )
        })


# ------------------------------------------------------------
# 5. Create Evaluation DataFrame
# ------------------------------------------------------------

evaluation_results_df = pd.DataFrame(
    evaluation_results
)


# ------------------------------------------------------------
# 6. Display Product-Level Results
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRODUCT-LEVEL MODEL PERFORMANCE")
print("=" * 70)

display(
    evaluation_results_df.round(2)
)


# ------------------------------------------------------------
# 7. Average Performance Across Products
# ------------------------------------------------------------

model_comparison = (
    evaluation_results_df
    .groupby('Model')
    .agg(
        Average_MAE=('MAE', 'mean'),
        Average_RMSE=('RMSE', 'mean'),
        Average_MAPE=('MAPE_%', 'mean')
    )
    .reset_index()
    .sort_values('Average_MAE')
)


print("\n" + "=" * 70)
print("OVERALL MODEL COMPARISON")
print("=" * 70)

display(
    model_comparison.round(2)
)


# ------------------------------------------------------------
# 8. Best-Performing Model by Product
# ------------------------------------------------------------

best_model_by_product = (
    evaluation_results_df
    .sort_values(
        ['Product_ID', 'MAE']
    )
    .groupby('Product_ID')
    .first()
    .reset_index()
)


print("\n" + "=" * 70)
print("LOWEST-MAE MODEL BY PRODUCT")
print("=" * 70)

display(
    best_model_by_product[
        [
            'Product_ID',
            'Model',
            'MAE',
            'RMSE',
            'MAPE_%'
        ]
    ].round(2)
)

======================================================================
DEMAND FORECASTING MODEL EVALUATION
======================================================================

======================================================================
PRODUCT-LEVEL MODEL PERFORMANCE
======================================================================

   Product_ID                    Model     MAE     RMSE  MAPE_%
0        P001   3-Month Moving Average  522.44   603.58   44.31
1        P001   6-Month Moving Average  533.04   688.02   45.45
2        P001  12-Month Seasonal Naive  655.33   891.10   43.77
3        P002   3-Month Moving Average  644.78   765.37   51.66
4        P002   6-Month Moving Average  576.14   694.09   47.81
5        P002  12-Month Seasonal Naive  988.83  1151.97   81.74
6        P003   3-Month Moving Average  603.17   727.53   42.36
7        P003   6-Month Moving Average  567.32   663.63   41.74
8        P003  12-Month Seasonal Naive  957.25  1129.15   77.36
9        P004   3-Month Moving Average  559.61   649.57   39.41
10       P004   6-Month Moving Average  588.07   680.96   40.60
11       P004  12-Month Seasonal Naive  647.58   805.70   39.37
12       P005   3-Month Moving Average  454.64   584.52   28.29
13       P005   6-Month Moving Average  460.58   591.99   27.69
14       P005  12-Month Seasonal Naive  714.25   977.00   45.35

======================================================================
OVERALL MODEL COMPARISON
======================================================================

                     Model  Average_MAE  Average_RMSE  Average_MAPE
2   6-Month Moving Average       545.03        663.74         40.66
1   3-Month Moving Average       556.93        666.12         41.21
0  12-Month Seasonal Naive       792.65        990.99         57.52

======================================================================
LOWEST-MAE MODEL BY PRODUCT
======================================================================

  Product_ID                   Model     MAE    RMSE  MAPE_%
0       P001  3-Month Moving Average  522.44  603.58   44.31
1       P002  6-Month Moving Average  576.14  694.09   47.81
2       P003  6-Month Moving Average  567.32  663.63   41.74
3       P004  3-Month Moving Average  559.61  649.57   39.41
4       P005  3-Month Moving Average  454.64  584.52   28.29

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 17: NEXT-MONTH DEMAND FORECAST
# ============================================================

print("=" * 70)
print("NEXT-MONTH DEMAND FORECAST")
print("=" * 70)


# ------------------------------------------------------------
# 1. Selected Model for Each Product
# ------------------------------------------------------------

selected_models = {
    'P001': '3-Month Moving Average',
    'P002': '6-Month Moving Average',
    'P003': '6-Month Moving Average',
    'P004': '3-Month Moving Average',
    'P005': '3-Month Moving Average'
}


# ------------------------------------------------------------
# 2. Forecast Target Month
# ------------------------------------------------------------

last_complete_month = forecast_data['Month'].max()

forecast_month = (
    last_complete_month +
    pd.DateOffset(months=1)
)

print("\nFORECAST PERIOD")
print("-" * 70)
print(
    f"Last Complete Month : "
    f"{last_complete_month.strftime('%Y-%m')}"
)
print(
    f"Forecast Month : "
    f"{forecast_month.strftime('%Y-%m')}"
)


# ------------------------------------------------------------
# 3. Generate Product-Level Forecasts
# ------------------------------------------------------------

forecast_results = []

for product in sorted(
    forecast_data['Product_ID'].unique()
):

    product_series = (
        forecast_data[
            forecast_data['Product_ID'] == product
        ]
        .sort_values('Month')
        .set_index('Month')['Quantity_Sold']
    )

    selected_model = selected_models[product]


    if selected_model == '3-Month Moving Average':

        recent_values = product_series.tail(3)

        forecast_value = recent_values.mean()

        window = 3


    elif selected_model == '6-Month Moving Average':

        recent_values = product_series.tail(6)

        forecast_value = recent_values.mean()

        window = 6


    forecast_results.append({
        'Product_ID': product,
        'Forecast_Month': forecast_month,
        'Model': selected_model,
        'Window_Months': window,
        'Forecast_Demand': forecast_value
    })


# ------------------------------------------------------------
# 4. Create Forecast DataFrame
# ------------------------------------------------------------

next_month_forecast = pd.DataFrame(
    forecast_results
)

next_month_forecast['Forecast_Demand'] = (
    next_month_forecast['Forecast_Demand']
    .round(0)
    .astype(int)
)


# ------------------------------------------------------------
# 5. Display Forecast
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRODUCT-LEVEL NEXT-MONTH FORECAST")
print("=" * 70)

display(
    next_month_forecast
)


# ------------------------------------------------------------
# 6. Total Forecasted Demand
# ------------------------------------------------------------

total_forecast_demand = (
    next_month_forecast['Forecast_Demand'].sum()
)

print("\n" + "=" * 70)
print("TOTAL FORECAST")
print("=" * 70)

print(
    f"Forecasted Total Demand for "
    f"{forecast_month.strftime('%Y-%m')} : "
    f"{total_forecast_demand:,} units"
)


# ------------------------------------------------------------
# 7. Show Historical Values Used
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("HISTORICAL DEMAND VALUES USED FOR FORECAST")
print("=" * 70)

forecast_inputs = []

for product in sorted(
    forecast_data['Product_ID'].unique()
):

    model = selected_models[product]

    window = (
        3
        if model == '3-Month Moving Average'
        else 6
    )

    product_history = (
        forecast_data[
            forecast_data['Product_ID'] == product
        ]
        .sort_values('Month')
        .tail(window)
        [['Product_ID', 'Month', 'Quantity_Sold']]
    )

    forecast_inputs.append(
        product_history
    )

forecast_inputs_df = pd.concat(
    forecast_inputs,
    ignore_index=True
)

display(
    forecast_inputs_df
)

======================================================================
NEXT-MONTH DEMAND FORECAST
======================================================================

FORECAST PERIOD
----------------------------------------------------------------------
Last Complete Month : 2037-08
Forecast Month : 2037-09

======================================================================
PRODUCT-LEVEL NEXT-MONTH FORECAST
======================================================================

,Product_ID,Forecast_Month,Model,Window_Months,Forecast_Demand
0,P001,2037-09-01,3-Month Moving Average,3,1170
1,P002,2037-09-01,6-Month Moving Average,6,1373
2,P003,2037-09-01,6-Month Moving Average,6,1345
3,P004,2037-09-01,3-Month Moving Average,3,1852
4,P005,2037-09-01,3-Month Moving Average,3,1466

======================================================================
TOTAL FORECAST
======================================================================
Forecasted Total Demand for 2037-09 : 7,206 units

======================================================================
HISTORICAL DEMAND VALUES USED FOR FORECAST
======================================================================

   Product_ID      Month  Quantity_Sold
0        P001 2037-06-01         1496.0
1        P001 2037-07-01          768.0
2        P001 2037-08-01         1245.0
3        P002 2037-03-01         1153.0
4        P002 2037-04-01         1768.0
5        P002 2037-05-01          863.0
6        P002 2037-06-01         1121.0
7        P002 2037-07-01         1626.0
8        P002 2037-08-01         1707.0
9        P003 2037-03-01         1456.0
10       P003 2037-04-01          913.0
11       P003 2037-05-01          910.0
12       P003 2037-06-01         2347.0
13       P003 2037-07-01          926.0
14       P003 2037-08-01         1519.0
15       P004 2037-06-01         1276.0
16       P004 2037-07-01         1449.0
17       P004 2037-08-01         2830.0
18       P005 2037-06-01         1345.0
19       P005 2037-07-01         1969.0
20       P005 2037-08-01         1084.0

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 18: REORDER POINT CALCULATION
# ============================================================

print("=" * 70)
print("REORDER POINT CALCULATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Product-Level Historical Demand Statistics
# ------------------------------------------------------------

demand_statistics = (
    forecast_data
    .groupby('Product_ID')
    .agg(
        Average_Monthly_Demand=('Quantity_Sold', 'mean'),
        Demand_Std_Dev_Monthly=('Quantity_Sold', 'std'),
        Total_Historical_Demand=('Quantity_Sold', 'sum')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 2. Convert Monthly Demand to Approximate Daily Demand
# ------------------------------------------------------------

demand_statistics['Average_Daily_Demand'] = (
    demand_statistics['Average_Monthly_Demand'] / 30
)


# ------------------------------------------------------------
# 3. Calculate Product-Level Supplier Lead Time
# ------------------------------------------------------------

product_lead_time = (
    suppliers
    .groupby('Product_ID')
    .agg(
        Supplier_Count=('Supplier_ID', 'nunique'),
        Average_Lead_Time_Days=('Lead_Time (days)', 'mean'),
        Minimum_Lead_Time_Days=('Lead_Time (days)', 'min'),
        Maximum_Lead_Time_Days=('Lead_Time (days)', 'max')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 4. Merge Demand and Lead-Time Information
# ------------------------------------------------------------

reorder_point_data = demand_statistics.merge(
    product_lead_time,
    on='Product_ID',
    how='left'
)


# ------------------------------------------------------------
# 5. Calculate Demand During Lead Time
# ------------------------------------------------------------

reorder_point_data['Lead_Time_Demand'] = (
    reorder_point_data['Average_Daily_Demand']
    *
    reorder_point_data['Average_Lead_Time_Days']
)


# ------------------------------------------------------------
# 6. Estimate Daily Demand Standard Deviation
# ------------------------------------------------------------

reorder_point_data['Demand_Std_Dev_Daily'] = (
    reorder_point_data['Demand_Std_Dev_Monthly']
    / np.sqrt(30)
)


# ------------------------------------------------------------
# 7. Calculate Safety Stock
# ------------------------------------------------------------
# Service-level assumption:
# 95% service level -> Z = 1.645

Z_VALUE = 1.645

reorder_point_data['Safety_Stock'] = (
    Z_VALUE
    *
    reorder_point_data['Demand_Std_Dev_Daily']
    *
    np.sqrt(
        reorder_point_data['Average_Lead_Time_Days']
    )
)


# ------------------------------------------------------------
# 8. Calculate Reorder Point
# ------------------------------------------------------------

reorder_point_data['Reorder_Point'] = (
    reorder_point_data['Lead_Time_Demand']
    +
    reorder_point_data['Safety_Stock']
)


# ------------------------------------------------------------
# 9. Round Operational Values
# ------------------------------------------------------------

numeric_columns = [
    'Average_Monthly_Demand',
    'Demand_Std_Dev_Monthly',
    'Average_Daily_Demand',
    'Average_Lead_Time_Days',
    'Minimum_Lead_Time_Days',
    'Maximum_Lead_Time_Days',
    'Lead_Time_Demand',
    'Demand_Std_Dev_Daily',
    'Safety_Stock',
    'Reorder_Point'
]

reorder_point_data[numeric_columns] = (
    reorder_point_data[numeric_columns]
    .round(2)
)


# ------------------------------------------------------------
# 10. Display Supplier Lead-Time Information
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRODUCT-LEVEL SUPPLIER LEAD TIME")
print("=" * 70)

display(
    product_lead_time.round(2)
)


# ------------------------------------------------------------
# 11. Display Reorder Point Calculation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("REORDER POINT RESULTS")
print("=" * 70)

display(
    reorder_point_data[
        [
            'Product_ID',
            'Average_Monthly_Demand',
            'Average_Daily_Demand',
            'Average_Lead_Time_Days',
            'Lead_Time_Demand',
            'Safety_Stock',
            'Reorder_Point'
        ]
    ]
)


# ------------------------------------------------------------
# 12. Display Formula Components
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("REORDER POINT FORMULA")
print("=" * 70)

print("Reorder Point = Lead-Time Demand + Safety Stock")
print("Lead-Time Demand = Average Daily Demand × Average Lead Time")
print("Safety Stock = Z × Daily Demand Std. Dev. × √Lead Time")
print("Service Level Assumption = 95%")
print("Z-Value = 1.645")

======================================================================
REORDER POINT CALCULATION
======================================================================

======================================================================
PRODUCT-LEVEL SUPPLIER LEAD TIME
======================================================================

,Product_ID,Supplier_Count,Average_Lead_Time_Days,Minimum_Lead_Time_Days,Maximum_Lead_Time_Days
0,P001,12,6.25,4,9
1,P002,12,6.67,3,9
2,P003,8,6.00,3,9
3,P004,6,6.00,4,9
4,P005,12,6.00,3,9

======================================================================
REORDER POINT RESULTS
======================================================================

,Product_ID,Average_Monthly_Demand,Average_Daily_Demand,Average_Lead_Time_Days,Lead_Time_Demand,Safety_Stock,Reorder_Point
0,P001,1584.90,52.83,6.25,330.19,546.53,876.72
1,P002,1640.85,54.70,6.67,364.63,539.41,904.05
2,P003,1517.70,50.59,6.00,303.54,463.32,766.86
3,P004,1572.50,52.42,6.00,314.50,502.95,817.45
4,P005,1551.97,51.73,6.00,310.39,495.41,805.81

======================================================================
REORDER POINT FORMULA
======================================================================
Reorder Point = Lead-Time Demand + Safety Stock
Lead-Time Demand = Average Daily Demand × Average Lead Time
Safety Stock = Z × Daily Demand Std. Dev. × √Lead Time
Service Level Assumption = 95%
Z-Value = 1.645

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 19: INVENTORY VS CALCULATED REORDER POINT
# ============================================================

print("=" * 70)
print("INVENTORY VS CALCULATED REORDER POINT")
print("=" * 70)


# ------------------------------------------------------------
# 1. Prepare Product-Level Reorder Point
# ------------------------------------------------------------

product_reorder_points = (
    reorder_point_data[
        [
            'Product_ID',
            'Average_Monthly_Demand',
            'Average_Lead_Time_Days',
            'Lead_Time_Demand',
            'Safety_Stock',
            'Reorder_Point'
        ]
    ]
    .copy()
)


# ------------------------------------------------------------
# 2. Aggregate Inventory by Product and Store
# ------------------------------------------------------------

inventory_product_store = (
    inventory
    .groupby(
        ['Product_ID', 'Store_ID'],
        as_index=False
    )
    .agg(
        Inventory_Records=('Product_ID', 'count'),
        Current_Stock=('Stock_Level', 'sum'),
        Existing_Reorder_Level=('Reorder_Level', 'sum')
    )
)


# ------------------------------------------------------------
# 3. Merge Calculated Reorder Point
# ------------------------------------------------------------

inventory_reorder_analysis = inventory_product_store.merge(
    product_reorder_points,
    on='Product_ID',
    how='left'
)


# ------------------------------------------------------------
# 4. Calculate Store-Level Reorder Requirement
# ------------------------------------------------------------

inventory_reorder_analysis['Calculated_Reorder_Point'] = (
    inventory_reorder_analysis['Reorder_Point']
)


inventory_reorder_analysis['Stock_vs_Calculated_Reorder'] = (
    inventory_reorder_analysis['Current_Stock']
    -
    inventory_reorder_analysis['Calculated_Reorder_Point']
)


inventory_reorder_analysis['Additional_Stock_Required'] = (
    inventory_reorder_analysis['Calculated_Reorder_Point']
    -
    inventory_reorder_analysis['Current_Stock']
).clip(lower=0)


inventory_reorder_analysis['Replenishment_Status'] = np.where(
    inventory_reorder_analysis['Current_Stock']
    <
    inventory_reorder_analysis['Calculated_Reorder_Point'],
    'Below Calculated Reorder Point',
    'At/Above Calculated Reorder Point'
)


# ------------------------------------------------------------
# 5. Round Values
# ------------------------------------------------------------

round_columns = [
    'Current_Stock',
    'Existing_Reorder_Level',
    'Average_Monthly_Demand',
    'Average_Lead_Time_Days',
    'Lead_Time_Demand',
    'Safety_Stock',
    'Calculated_Reorder_Point',
    'Stock_vs_Calculated_Reorder',
    'Additional_Stock_Required'
]

inventory_reorder_analysis[round_columns] = (
    inventory_reorder_analysis[round_columns]
    .round(2)
)


# ------------------------------------------------------------
# 6. Display Complete Analysis
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRODUCT-STORE REORDER ANALYSIS")
print("=" * 70)

display(
    inventory_reorder_analysis[
        [
            'Product_ID',
            'Store_ID',
            'Current_Stock',
            'Existing_Reorder_Level',
            'Calculated_Reorder_Point',
            'Stock_vs_Calculated_Reorder',
            'Additional_Stock_Required',
            'Replenishment_Status'
        ]
    ]
)


# ------------------------------------------------------------
# 7. Replenishment Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("REPLENISHMENT SUMMARY")
print("=" * 70)

replenishment_summary = (
    inventory_reorder_analysis
    .groupby('Replenishment_Status')
    .agg(
        Product_Store_Records=('Product_ID', 'count'),
        Total_Current_Stock=('Current_Stock', 'sum'),
        Total_Additional_Stock_Required=(
            'Additional_Stock_Required',
            'sum'
        )
    )
    .reset_index()
)

display(
    replenishment_summary.round(2)
)


# ------------------------------------------------------------
# 8. Count Replenishment Records
# ------------------------------------------------------------

below_calculated = (
    inventory_reorder_analysis[
        inventory_reorder_analysis['Replenishment_Status']
        ==
        'Below Calculated Reorder Point'
    ]
)

print(
    f"\nRecords Below Calculated Reorder Point : "
    f"{len(below_calculated)}"
)

print(
    f"Records At/Above Calculated Reorder Point : "
    f"{len(inventory_reorder_analysis) - len(below_calculated)}"
)


# ------------------------------------------------------------
# 9. Highest Replenishment Requirements
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("HIGHEST ADDITIONAL STOCK REQUIREMENTS")
print("=" * 70)

display(
    inventory_reorder_analysis
    .sort_values(
        'Additional_Stock_Required',
        ascending=False
    )
    .head(15)[
        [
            'Product_ID',
            'Store_ID',
            'Current_Stock',
            'Calculated_Reorder_Point',
            'Additional_Stock_Required',
            'Replenishment_Status'
        ]
    ]
)

======================================================================
INVENTORY VS CALCULATED REORDER POINT
======================================================================

======================================================================
PRODUCT-STORE REORDER ANALYSIS
======================================================================

,Product_ID,Store_ID,Current_Stock,Existing_Reorder_Level,Calculated_Reorder_Point,Stock_vs_Calculated_Reorder,Additional_Stock_Required,Replenishment_Status
0,P001,S101,1601,1148,876.72,724.28,0.0,At/Above Calculated Reorder Point
1,P001,S102,1823,944,876.72,946.28,0.0,At/Above Calculated Reorder Point
2,P001,S103,2918,1756,876.72,2041.28,0.0,At/Above Calculated Reorder Point
3,P001,S104,2907,1432,876.72,2030.28,0.0,At/Above Calculated Reorder Point
4,P002,S101,3544,1899,904.05,2639.95,0.0,At/Above Calculated Reorder Point
5,P002,S102,3200,1446,904.05,2295.95,0.0,At/Above Calculated Reorder Point
6,P002,S103,1776,882,904.05,871.95,0.0,At/Above Calculated Reorder Point
7,P002,S104,1121,571,904.05,216.95,0.0,At/Above Calculated Reorder Point
8,P003,S101,3647,2266,766.86,2880.14,0.0,At/Above Calculated Reorder Point
9,P003,S102,3029,2047,766.86,2262.14,0.0,At/Above Calculated Reorder Point
10,P003,S103,2627,923,766.86,1860.14,0.0,At/Above Calculated Reorder Point
11,P003,S104,2178,1302,766.86,1411.14,0.0,At/Above Calculated Reorder Point
12,P004,S101,1319,997,817.45,501.55,0.0,At/Above Calculated Reorder Point
13,P004,S102,2695,1341,817.45,1877.55,0.0,At/Above Calculated Reorder Point
14,P004,S103,2338,1355,817.45,1520.55,0.0,At/Above Calculated Reorder Point
15,P004,S104,1628,643,817.45,810.55,0.0,At/Above Calculated Reorder Point
16,P005,S101,2137,1280,805.81,1331.19,0.0,At/Above Calculated Reorder Point
17,P005,S102,931,457,805.81,125.19,0.0,At/Above Calculated Reorder Point
18,P005,S103,2109,1091,805.81,1303.19,0.0,At/Above Calculated Reorder Point
19,P005,S104,1463,1178,805.81,657.19,0.0,At/Above Calculated Reorder Point

======================================================================
REPLENISHMENT SUMMARY
======================================================================

,Replenishment_Status,Product_Store_Records,Total_Current_Stock,Total_Additional_Stock_Required
0,At/Above Calculated Reorder Point,20,44991,0.0

Records Below Calculated Reorder Point : 0
Records At/Above Calculated Reorder Point : 20

======================================================================
HIGHEST ADDITIONAL STOCK REQUIREMENTS
======================================================================

,Product_ID,Store_ID,Current_Stock,Calculated_Reorder_Point,Additional_Stock_Required,Replenishment_Status
0,P001,S101,1601,876.72,0.0,At/Above Calculated Reorder Point
1,P001,S102,1823,876.72,0.0,At/Above Calculated Reorder Point
2,P001,S103,2918,876.72,0.0,At/Above Calculated Reorder Point
3,P001,S104,2907,876.72,0.0,At/Above Calculated Reorder Point
4,P002,S101,3544,904.05,0.0,At/Above Calculated Reorder Point
5,P002,S102,3200,904.05,0.0,At/Above Calculated Reorder Point
6,P002,S103,1776,904.05,0.0,At/Above Calculated Reorder Point
7,P002,S104,1121,904.05,0.0,At/Above Calculated Reorder Point
8,P003,S101,3647,766.86,0.0,At/Above Calculated Reorder Point
9,P003,S102,3029,766.86,0.0,At/Above Calculated Reorder Point
10,P003,S103,2627,766.86,0.0,At/Above Calculated Reorder Point
11,P003,S104,2178,766.86,0.0,At/Above Calculated Reorder Point
12,P004,S101,1319,817.45,0.0,At/Above Calculated Reorder Point
13,P004,S102,2695,817.45,0.0,At/Above Calculated Reorder Point
14,P004,S103,2338,817.45,0.0,At/Above Calculated Reorder Point

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 20: EXISTING VS CALCULATED REORDER LEVEL
# ============================================================

print("=" * 70)
print("EXISTING VS CALCULATED REORDER LEVEL")
print("=" * 70)


# ------------------------------------------------------------
# 1. Aggregate Existing Inventory Reorder Levels by Product
# ------------------------------------------------------------

existing_reorder_by_product = (
    inventory
    .groupby('Product_ID')
    .agg(
        Inventory_Records=('Product_ID', 'count'),
        Total_Current_Stock=('Stock_Level', 'sum'),
        Average_Current_Stock=('Stock_Level', 'mean'),
        Existing_Reorder_Level=('Reorder_Level', 'mean'),
        Total_Reorder_Level=('Reorder_Level', 'sum')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 2. Prepare Calculated Reorder Point
# ------------------------------------------------------------

calculated_rop = (
    reorder_point_data[
        [
            'Product_ID',
            'Average_Monthly_Demand',
            'Average_Lead_Time_Days',
            'Lead_Time_Demand',
            'Safety_Stock',
            'Reorder_Point'
        ]
    ]
    .copy()
    .rename(
        columns={
            'Reorder_Point': 'Calculated_Reorder_Point'
        }
    )
)


# ------------------------------------------------------------
# 3. Merge Existing and Calculated Reorder Levels
# ------------------------------------------------------------

reorder_level_comparison = existing_reorder_by_product.merge(
    calculated_rop,
    on='Product_ID',
    how='left'
)


# ------------------------------------------------------------
# 4. Calculate Difference
# ------------------------------------------------------------

reorder_level_comparison['Reorder_Level_Difference'] = (
    reorder_level_comparison['Calculated_Reorder_Point']
    -
    reorder_level_comparison['Existing_Reorder_Level']
)


reorder_level_comparison['Difference_Percentage'] = (
    reorder_level_comparison['Reorder_Level_Difference']
    /
    reorder_level_comparison['Existing_Reorder_Level']
) * 100


# ------------------------------------------------------------
# 5. Classify the Difference
# ------------------------------------------------------------

reorder_level_comparison['Threshold_Comparison'] = np.select(
    [
        reorder_level_comparison['Reorder_Level_Difference'] > 0,
        reorder_level_comparison['Reorder_Level_Difference'] < 0
    ],
    [
        'Calculated ROP Higher',
        'Calculated ROP Lower'
    ],
    default='Same'
)


# ------------------------------------------------------------
# 6. Round Numeric Values
# ------------------------------------------------------------

numeric_columns = [
    'Total_Current_Stock',
    'Average_Current_Stock',
    'Existing_Reorder_Level',
    'Total_Reorder_Level',
    'Average_Monthly_Demand',
    'Average_Lead_Time_Days',
    'Lead_Time_Demand',
    'Safety_Stock',
    'Calculated_Reorder_Point',
    'Reorder_Level_Difference',
    'Difference_Percentage'
]

reorder_level_comparison[numeric_columns] = (
    reorder_level_comparison[numeric_columns]
    .round(2)
)


# ------------------------------------------------------------
# 7. Product-Level Comparison
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRODUCT-LEVEL REORDER LEVEL COMPARISON")
print("=" * 70)

display(
    reorder_level_comparison[
        [
            'Product_ID',
            'Existing_Reorder_Level',
            'Calculated_Reorder_Point',
            'Reorder_Level_Difference',
            'Difference_Percentage',
            'Threshold_Comparison'
        ]
    ]
)


# ------------------------------------------------------------
# 8. Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("THRESHOLD COMPARISON SUMMARY")
print("=" * 70)

comparison_summary = (
    reorder_level_comparison
    .groupby('Threshold_Comparison')
    .agg(
        Product_Count=('Product_ID', 'count'),
        Average_Difference=('Reorder_Level_Difference', 'mean'),
        Average_Difference_Percentage=('Difference_Percentage', 'mean')
    )
    .reset_index()
)

display(
    comparison_summary.round(2)
)


# ------------------------------------------------------------
# 9. Current Stock vs Both Thresholds
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CURRENT STOCK VS BOTH REORDER THRESHOLDS")
print("=" * 70)

display(
    reorder_level_comparison[
        [
            'Product_ID',
            'Average_Current_Stock',
            'Existing_Reorder_Level',
            'Calculated_Reorder_Point',
            'Reorder_Level_Difference'
        ]
    ]
)

======================================================================
EXISTING VS CALCULATED REORDER LEVEL
======================================================================

======================================================================
PRODUCT-LEVEL REORDER LEVEL COMPARISON
======================================================================

,Product_ID,Existing_Reorder_Level,Calculated_Reorder_Point,Reorder_Level_Difference,Difference_Percentage,Threshold_Comparison
0,P001,132.00,876.72,744.72,564.18,Calculated ROP Higher
1,P002,123.03,904.05,781.02,634.85,Calculated ROP Higher
2,P003,128.20,766.86,638.66,498.19,Calculated ROP Higher
3,P004,120.44,817.45,697.01,578.69,Calculated ROP Higher
4,P005,117.82,805.81,687.99,583.91,Calculated ROP Higher

======================================================================
THRESHOLD COMPARISON SUMMARY
======================================================================

,Threshold_Comparison,Product_Count,Average_Difference,Average_Difference_Percentage
0,Calculated ROP Higher,5,709.88,571.96

======================================================================
CURRENT STOCK VS BOTH REORDER THRESHOLDS
======================================================================

,Product_ID,Average_Current_Stock,Existing_Reorder_Level,Calculated_Reorder_Point,Reorder_Level_Difference
0,P001,231.22,132.00,876.72,744.72
1,P002,247.21,123.03,904.05,781.02
2,P003,225.12,128.20,766.86,638.66
3,P004,221.67,120.44,817.45,697.01
4,P005,195.29,117.82,805.81,687.99

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 21: PRODUCT-LEVEL INVENTORY OPTIMIZATION ANALYSIS
# ============================================================

print("=" * 70)
print("PRODUCT-LEVEL INVENTORY OPTIMIZATION ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Create Next-Month Forecast DataFrame
# ------------------------------------------------------------

forecast_next_month = pd.DataFrame({
    'Product_ID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    'Forecast_Quantity': [1170, 1373, 1345, 1852, 1466],
    'Forecast_Method': [
        '3-Month Moving Average',
        '6-Month Moving Average',
        '6-Month Moving Average',
        '3-Month Moving Average',
        '3-Month Moving Average'
    ]
})


# ------------------------------------------------------------
# 2. Aggregate Current Inventory by Product
# ------------------------------------------------------------

product_inventory = (
    inventory
    .groupby('Product_ID')
    .agg(
        Inventory_Records=('Product_ID', 'count'),
        Total_Current_Stock=('Stock_Level', 'sum'),
        Average_Current_Stock=('Stock_Level', 'mean'),
        Existing_Reorder_Level=('Reorder_Level', 'mean')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 3. Prepare Calculated Reorder Point
# ------------------------------------------------------------

calculated_reorder = (
    reorder_point_data[
        [
            'Product_ID',
            'Average_Daily_Demand',
            'Average_Lead_Time_Days',
            'Lead_Time_Demand',
            'Safety_Stock',
            'Reorder_Point'
        ]
    ]
    .copy()
)


# ------------------------------------------------------------
# 4. Merge Inventory + Forecast + Reorder Point
# ------------------------------------------------------------

inventory_optimization = (
    product_inventory
    .merge(
        forecast_next_month,
        on='Product_ID',
        how='left'
    )
    .merge(
        calculated_reorder,
        on='Product_ID',
        how='left'
    )
)


# ------------------------------------------------------------
# 5. Calculate Inventory Metrics
# ------------------------------------------------------------

inventory_optimization['Stock_After_Forecast'] = (
    inventory_optimization['Total_Current_Stock']
    -
    inventory_optimization['Forecast_Quantity']
)


inventory_optimization['Stock_vs_ROP'] = (
    inventory_optimization['Total_Current_Stock']
    -
    inventory_optimization['Reorder_Point']
)


inventory_optimization['Forecast_vs_ROP'] = (
    inventory_optimization['Forecast_Quantity']
    -
    inventory_optimization['Reorder_Point']
)


# ------------------------------------------------------------
# 6. Inventory Status
# ------------------------------------------------------------

inventory_optimization['Inventory_Status'] = np.select(
    [
        inventory_optimization['Total_Current_Stock']
        <
        inventory_optimization['Reorder_Point'],

        inventory_optimization['Stock_After_Forecast']
        <
        0
    ],
    [
        'Below Calculated ROP',
        'Forecast Exceeds Current Stock'
    ],
    default='Above Calculated ROP'
)


# ------------------------------------------------------------
# 7. Round Numeric Values
# ------------------------------------------------------------

numeric_columns = [
    'Total_Current_Stock',
    'Average_Current_Stock',
    'Existing_Reorder_Level',
    'Forecast_Quantity',
    'Average_Daily_Demand',
    'Average_Lead_Time_Days',
    'Lead_Time_Demand',
    'Safety_Stock',
    'Reorder_Point',
    'Stock_After_Forecast',
    'Stock_vs_ROP',
    'Forecast_vs_ROP'
]

inventory_optimization[numeric_columns] = (
    inventory_optimization[numeric_columns]
    .round(2)
)


# ------------------------------------------------------------
# 8. Display Product-Level Analysis
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PRODUCT-LEVEL INVENTORY OPTIMIZATION")
print("=" * 70)

display(
    inventory_optimization[
        [
            'Product_ID',
            'Total_Current_Stock',
            'Existing_Reorder_Level',
            'Reorder_Point',
            'Forecast_Quantity',
            'Stock_After_Forecast',
            'Stock_vs_ROP',
            'Inventory_Status'
        ]
    ]
)


# ------------------------------------------------------------
# 9. Summary Statistics
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INVENTORY OPTIMIZATION SUMMARY")
print("=" * 70)

print(
    f"Total Products Analyzed : "
    f"{len(inventory_optimization)}"
)

print(
    f"Total Current Stock : "
    f"{inventory_optimization['Total_Current_Stock'].sum():,.0f}"
)

print(
    f"Total Next-Month Forecast : "
    f"{inventory_optimization['Forecast_Quantity'].sum():,.0f}"
)

print(
    f"Total Stock After Forecast : "
    f"{inventory_optimization['Stock_After_Forecast'].sum():,.0f}"
)


# ------------------------------------------------------------
# 10. Inventory Status Distribution
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INVENTORY STATUS DISTRIBUTION")
print("=" * 70)

status_summary = (
    inventory_optimization
    .groupby('Inventory_Status')
    .size()
    .reset_index(name='Product_Count')
)

display(status_summary)


# ------------------------------------------------------------
# 11. Forecast vs Current Stock
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FORECAST VS CURRENT STOCK")
print("=" * 70)

display(
    inventory_optimization[
        [
            'Product_ID',
            'Total_Current_Stock',
            'Forecast_Quantity',
            'Stock_After_Forecast'
        ]
    ]
    .sort_values(
        'Stock_After_Forecast'
    )
)

======================================================================
PRODUCT-LEVEL INVENTORY OPTIMIZATION ANALYSIS
======================================================================

======================================================================
PRODUCT-LEVEL INVENTORY OPTIMIZATION
======================================================================

,Product_ID,Total_Current_Stock,Existing_Reorder_Level,Reorder_Point,Forecast_Quantity,Stock_After_Forecast,Stock_vs_ROP,Inventory_Status
0,P001,9249,132.00,876.72,1170,8079,8372.28,Above Calculated ROP
1,P002,9641,123.03,904.05,1373,8268,8736.95,Above Calculated ROP
2,P003,11481,128.20,766.86,1345,10136,10714.14,Above Calculated ROP
3,P004,7980,120.44,817.45,1852,6128,7162.55,Above Calculated ROP
4,P005,6640,117.82,805.81,1466,5174,5834.19,Above Calculated ROP

======================================================================
INVENTORY OPTIMIZATION SUMMARY
======================================================================
Total Products Analyzed : 5
Total Current Stock : 44,991
Total Next-Month Forecast : 7,206
Total Stock After Forecast : 37,785

======================================================================
INVENTORY STATUS DISTRIBUTION
======================================================================

       Inventory_Status  Product_Count
0  Above Calculated ROP              5

======================================================================
FORECAST VS CURRENT STOCK
======================================================================

  Product_ID  Total_Current_Stock  Forecast_Quantity  Stock_After_Forecast
4       P005                 6640               1466                  5174
3       P004                 7980               1852                  6128
0       P001                 9249               1170                  8079
1       P002                 9641               1373                  8268
2       P003                11481               1345                 10136

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 22: FINAL PRODUCT-LEVEL SUPPLY CHAIN ANALYTICS DATASET
# ============================================================

print("=" * 70)
print("FINAL PRODUCT-LEVEL SUPPLY CHAIN ANALYTICS DATASET")
print("=" * 70)


# ------------------------------------------------------------
# 1. Product-Level Sales Summary
# ------------------------------------------------------------

product_sales_summary = (
    sales
    .groupby('Product_ID')
    .agg(
        Total_Transactions=('Sale_ID', 'count'),
        Total_Quantity_Sold=('Quantity_Sold', 'sum'),
        Total_Revenue=('Revenue', 'sum'),
        Average_Quantity_Per_Transaction=('Quantity_Sold', 'mean')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 2. Product-Level Inventory Summary
# ------------------------------------------------------------

product_inventory_summary = (
    inventory
    .groupby('Product_ID')
    .agg(
        Inventory_Records=('Product_ID', 'count'),
        Total_Current_Stock=('Stock_Level', 'sum'),
        Average_Current_Stock=('Stock_Level', 'mean'),
        Existing_Reorder_Level=('Reorder_Level', 'mean'),
        Below_Reorder_Records=(
            'Stock_Level',
            lambda x: 0
        )
    )
    .reset_index()
)

# Calculate actual below-reorder records separately
below_reorder_counts = (
    inventory
    .assign(
        Below_Reorder=lambda x:
        x['Stock_Level'] < x['Reorder_Level']
    )
    .groupby('Product_ID')['Below_Reorder']
    .sum()
    .reset_index(name='Below_Reorder_Records')
)

product_inventory_summary = (
    product_inventory_summary
    .drop(columns='Below_Reorder_Records')
    .merge(
        below_reorder_counts,
        on='Product_ID',
        how='left'
    )
)


# ------------------------------------------------------------
# 3. Supplier Lead-Time Summary
# ------------------------------------------------------------

product_supplier_summary = (
    suppliers
    .groupby('Product_ID')
    .agg(
        Supplier_Count=('Supplier_ID', 'nunique'),
        Average_Supplier_Lead_Time=(
            'Lead_Time (days)',
            'mean'
        ),
        Minimum_Supplier_Lead_Time=(
            'Lead_Time (days)',
            'min'
        ),
        Maximum_Supplier_Lead_Time=(
            'Lead_Time (days)',
            'max'
        )
    )
    .reset_index()
)


# ------------------------------------------------------------
# 4. Purchase Order Summary
# ------------------------------------------------------------

product_po_summary = (
    purchase_orders
    .groupby('Product_ID')
    .agg(
        Total_Purchase_Orders=('Order_ID', 'count'),
        Total_Quantity_Ordered=('Quantity', 'sum'),
        Average_Order_Quantity=('Quantity', 'mean')
    )
    .reset_index()
)


# ------------------------------------------------------------
# 5. Prepare Forecast Data
# ------------------------------------------------------------

final_forecast = forecast_next_month[
    [
        'Product_ID',
        'Forecast_Quantity',
        'Forecast_Method'
    ]
].copy()


# ------------------------------------------------------------
# 6. Prepare Reorder Point Data
# ------------------------------------------------------------

final_rop = reorder_point_data[
    [
        'Product_ID',
        'Average_Monthly_Demand',
        'Average_Daily_Demand',
        'Demand_Std_Dev_Monthly',
        'Average_Lead_Time_Days',
        'Lead_Time_Demand',
        'Safety_Stock',
        'Reorder_Point'
    ]
].copy()


# ------------------------------------------------------------
# 7. Merge All Product-Level Components
# ------------------------------------------------------------

final_product_analytics = (
    product_sales_summary
    .merge(
        product_inventory_summary,
        on='Product_ID',
        how='left'
    )
    .merge(
        product_supplier_summary,
        on='Product_ID',
        how='left'
    )
    .merge(
        product_po_summary,
        on='Product_ID',
        how='left'
    )
    .merge(
        final_forecast,
        on='Product_ID',
        how='left'
    )
    .merge(
        final_rop,
        on='Product_ID',
        how='left'
    )
)


# ------------------------------------------------------------
# 8. Calculate Additional KPIs
# ------------------------------------------------------------

final_product_analytics['Revenue_Per_Unit'] = (
    final_product_analytics['Total_Revenue']
    /
    final_product_analytics['Total_Quantity_Sold']
)


final_product_analytics['Stock_After_Forecast'] = (
    final_product_analytics['Total_Current_Stock']
    -
    final_product_analytics['Forecast_Quantity']
)


final_product_analytics['Stock_vs_ROP'] = (
    final_product_analytics['Total_Current_Stock']
    -
    final_product_analytics['Reorder_Point']
)


final_product_analytics['Forecast_vs_ROP'] = (
    final_product_analytics['Forecast_Quantity']
    -
    final_product_analytics['Reorder_Point']
)


final_product_analytics['Inventory_Risk_Percentage'] = (
    final_product_analytics['Below_Reorder_Records']
    /
    final_product_analytics['Inventory_Records']
) * 100


# ------------------------------------------------------------
# 9. Demand Classification
# ------------------------------------------------------------

median_demand = (
    final_product_analytics['Total_Quantity_Sold']
    .median()
)

final_product_analytics['Demand_Category'] = np.where(
    final_product_analytics['Total_Quantity_Sold']
    >= median_demand,
    'High Demand',
    'Lower Demand'
)


# ------------------------------------------------------------
# 10. Reorder Risk Classification
# ------------------------------------------------------------

median_inventory_risk = (
    final_product_analytics['Inventory_Risk_Percentage']
    .median()
)

final_product_analytics['Reorder_Risk_Category'] = np.where(
    final_product_analytics['Inventory_Risk_Percentage']
    >= median_inventory_risk,
    'Higher Risk',
    'Lower Risk'
)


# ------------------------------------------------------------
# 11. Final Inventory Status
# ------------------------------------------------------------

final_product_analytics['Final_Inventory_Status'] = np.where(
    final_product_analytics['Total_Current_Stock']
    <
    final_product_analytics['Reorder_Point'],
    'Below Calculated ROP',
    'Above Calculated ROP'
)


# ------------------------------------------------------------
# 12. Round Numeric Columns
# ------------------------------------------------------------

numeric_columns = [
    'Total_Quantity_Sold',
    'Total_Revenue',
    'Average_Quantity_Per_Transaction',
    'Total_Current_Stock',
    'Average_Current_Stock',
    'Existing_Reorder_Level',
    'Average_Supplier_Lead_Time',
    'Minimum_Supplier_Lead_Time',
    'Maximum_Supplier_Lead_Time',
    'Total_Quantity_Ordered',
    'Average_Order_Quantity',
    'Forecast_Quantity',
    'Average_Monthly_Demand',
    'Average_Daily_Demand',
    'Demand_Std_Dev_Monthly',
    'Average_Lead_Time_Days',
    'Lead_Time_Demand',
    'Safety_Stock',
    'Reorder_Point',
    'Revenue_Per_Unit',
    'Stock_After_Forecast',
    'Stock_vs_ROP',
    'Forecast_vs_ROP',
    'Inventory_Risk_Percentage'
]

final_product_analytics[numeric_columns] = (
    final_product_analytics[numeric_columns]
    .round(2)
)


# ------------------------------------------------------------
# 13. Display Final Dataset
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL PRODUCT-LEVEL ANALYTICS")
print("=" * 70)

display(
    final_product_analytics
    .sort_values(
        'Total_Quantity_Sold',
        ascending=False
    )
)


# ------------------------------------------------------------
# 14. Dataset Validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL DATASET VALIDATION")
print("=" * 70)

print(
    f"Number of Products : "
    f"{final_product_analytics['Product_ID'].nunique()}"
)

print(
    f"Number of Rows : "
    f"{len(final_product_analytics)}"
)

print(
    f"Missing Values : "
    f"{final_product_analytics.isna().sum().sum()}"
)

print(
    f"Duplicate Rows : "
    f"{final_product_analytics.duplicated().sum()}"
)

======================================================================
FINAL PRODUCT-LEVEL SUPPLY CHAIN ANALYTICS DATASET
======================================================================

======================================================================
FINAL PRODUCT-LEVEL ANALYTICS
======================================================================

,Product_ID,Total_Transactions,Total_Quantity_Sold,Total_Revenue,Average_Quantity_Per_Transaction,Inventory_Records,Total_Current_Stock,Average_Current_Stock,Existing_Reorder_Level,Below_Reorder_Records,...,Safety_Stock,Reorder_Point,Revenue_Per_Unit,Stock_After_Forecast,Stock_vs_ROP,Forecast_vs_ROP,Inventory_Risk_Percentage,Demand_Category,Reorder_Risk_Category,Final_Inventory_Status
1,P002,1018,269100,26084882,264.34,39,9641,247.21,123.03,8,...,539.41,904.05,96.93,8268,8736.95,468.95,20.51,High Demand,Lower Risk,Above Calculated ROP
0,P001,1044,260296,25355109,249.33,40,9249,231.22,132.00,10,...,546.53,876.72,97.41,8079,8372.28,293.28,25.00,High Demand,Lower Risk,Above Calculated ROP
3,P004,985,258635,24835649,262.57,36,7980,221.67,120.44,12,...,502.95,817.45,96.03,6128,7162.55,1034.55,33.33,High Demand,Higher Risk,Above Calculated ROP
4,P005,973,254794,24896449,261.86,34,6640,195.29,117.82,9,...,495.41,805.81,97.71,5174,5834.19,660.19,26.47,Lower Demand,Higher Risk,Above Calculated ROP
2,P003,980,249297,24697925,254.38,51,11481,225.12,128.20,14,...,463.32,766.86,99.07,10136,10714.14,578.14,27.45,Lower Demand,Higher Risk,Above Calculated ROP

======================================================================
FINAL DATASET VALIDATION
======================================================================
Number of Products : 5
Number of Rows : 5
Missing Values : 0
Duplicate Rows : 0

In [ ]:
# ============================================================
# CASE STUDY 6
# STEP 23: EXPORT FINAL PRODUCT ANALYTICS DATASET
# ============================================================

output_file = 'case_study_6_final_product_analytics.csv'

final_product_analytics.to_csv(
    output_file,
    index=False
)

print("=" * 70)
print("FINAL DATASET EXPORTED")
print("=" * 70)

print(f"File Name : {output_file}")
print(
    f"Rows : {len(final_product_analytics)}"
)
print(
    f"Columns : {len(final_product_analytics.columns)}"
)

print("\nExport Status : SUCCESS")

======================================================================
FINAL DATASET EXPORTED
======================================================================
File Name : case_study_6_final_product_analytics.csv
Rows : 5
Columns : 34

Export Status : SUCCESS